### ISSUE TITLE
Вызов функционального компонента с передачей пропс по событию, вызванному в  ячейке таблицы

### ISSUE THREAD

**Issue by vbogachev1982** [AdmiralDS/react-ui#1009]
Добрый вечер
Подскажите , возможно в render_cell для элемента с событием вызвать компонент, с передачей в него пропсов (текущая строка), возвращающий ,например, модальное окно с какими либо данными (Вызвать модальное окно по клику на элемент в ячейке таблицы?

**Comment by kateviditory** [comment]
<img width="580" alt="Снимок экрана 2023-07-12 в 16 18 20" src="https://github.com/AdmiralDS/react-ui/assets/23409575/708cf39c-e8d7-4553-8870-7032058e016d">

Добрый день! Таблица предоставляет для использования renderCell колбек, с помощью которого вы можете отрисовать в ячейке таблицы любой контент на своё усмотрение. В том числе вы можете отрисовать некий компонент, который при клике на себя, будет открывать модальное окно. 

Колбек renderCell имеет 3 входных параметра: data - контент ячейки (то, что у вас указано в rowList для данной ячейки), row - объект строки целиком (объект, который задан в rowList) и rowIdx - индекс строки. Все эти параметры вы можете передать в свой компонент, открывающий модалку, в качестве пропсов.

**Comment by kateviditory** [comment]
В связи с отсутствием дальнейшей активности со стороны пользователя закрываю данное issue.
