### ISSUE TITLE
TextField - некорректная работа maxRows с autoHeight

### ISSUE THREAD

**Issue by J-N-Z** [AdmiralDS/react-ui#1020]
При использовании maxRows с autoHeight, если в поле хранится длинный текст, например по высоте maxRows или больше, при первом рендере поле сжато по высоте, скролл внутри не отображается, таким образом, нет возможности увидеть полный текст, но если начать ввод в поле, оно раскрывается, отображая полный текст.

**Comment by DrUNE** [comment]
Не удалось воспроизвести вот тут [https://stackblitz.com/edit/github-gnnzzn-etlpfw?file=pages%2Fdocumentation%2Fselect.tsx](https://stackblitz.com/edit/github-gnnzzn-etlpfw?file=pages%2Fdocumentation%2Fselect.tsx), попробуйте изменить пример для воспроизведения или дайте ссылку на минимальный рабочий проект. Минимальный настроенный рабочий проект можно зачекаутить тут [https://github.com/AdmiralDS/web-app-vite-admiral](https://github.com/AdmiralDS/web-app-vite-admiral)

**Comment by J-N-Z** [comment]
https://stackblitz.com/edit/github-gnnzzn-3tt2xu?file=pages%2Fdocumentation%2Fselect.tsx

Обновил. Воспроизводится, для этого значение поля должно прийти асинхронно. Добавил в пример через setTimeout/useEffect
