### ISSUE TITLE
Fix - Tree - неправильная работа с пустым массивом children

### ISSUE THREAD

**Issue by syros** [AdmiralDS/react-ui#1032]
При пустом массиве children показан chevron и если есть checkbox, то он в состоянии checked

**Comment by taraswww777** [comment]
```
Нормальное ли поведение у Tree при непроставленном свойстве checked и пустом массиве children? Сейчас такие TreeNodeProps отображаются выделенными, хотя не должны.
```

![photo_2023-07-19_17-37-25](https://github.com/AdmiralDS/react-ui/assets/13847428/abca4cbe-7927-42a8-acf8-f6d32cfb32cc)
![photo_2023-07-19_17-37-38](https://github.com/AdmiralDS/react-ui/assets/13847428/b2f4dc08-fa69-4831-a8a7-786a7193cc62)
