### ISSUE TITLE
Странное поведение компонента Select в режиме "searchSelect"

### ISSUE THREAD

**Issue by re45h8** [AdmiralDS/react-ui#1062]
Пероидически при скролле содержимое компонента скроллится вверх, хотя по идее должно всегда вниз. Есть моё личное предположение, что скролл происходит к последнему элементу, который был выделен при ховере по нему. Данный "возврат" хорошо заметен на отрезке 38-42 когда нас возвращает с 170* на 129*.

Бразуер - Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)

https://github.com/AdmiralDS/react-ui/assets/141011041/ef02aeb8-514b-4e70-a57f-14e361cdbbb3

**Comment by syros** [comment]
Дублирование #951 
Отслеживайте в той задаче.
