### ISSUE TITLE
Slider - добавить свойство stickyTickMarks=false, чтобы при указании tickMarks выбираемое значение не прилипало к ближайшему из tickMarks

### ISSUE THREAD

**Issue by gh-igor** [AdmiralDS/react-ui#1067]
Например, так:
[0001-feat-Slider-add-stickyTickMarks-to-Slider.patch.zip](https://github.com/AdmiralDS/react-ui/files/12225721/0001-feat-Slider-add-stickyTickMarks-to-Slider.patch.zip)

**Comment by kateviditory** [comment]
Добрый день, на данный момент наша дизайн-система не предусматривает описанного вами поведения (прилагаю скрин макетов).
<img width="785" alt="Снимок экрана 2023-08-01 в 17 15 31" src="https://github.com/AdmiralDS/react-ui/assets/23409575/6c7a974f-f95a-47aa-b71d-2f8db6862e6c">

Передам вопрос добавления подобного функционала на рассмотрение нашему дизайнеру.

**Comment by Eldar-Gyzyev** [comment]
Добрый день! Смысл этого компонента именно в том, что бы пользователь мог по определенным шагам перемещать ползунок. Если нужны произвольные значения, то выбирается слайдер с двумя крайними значениями и возможностью ввода любого значения из диапазона.

**Comment by gh-igor** [comment]
Согласен, но наш бизнес-кейс заключается в том, чтобы с одной стороны облегчить выбор значения из имеющихся и с другой стороны не препятствовать более гибкому поведению, потому что не всегда можно уместить все лейбы, которые нужны пользователю, поскольку у лейбы может быть подпись, например
![image](https://github.com/AdmiralDS/react-ui/assets/74675573/c71abc35-3820-4c0b-bcc7-40114ef6203b)
здесь еще позиционирование прихрамывает

**Comment by Eldar-Gyzyev** [comment]
Повторюсь – это не целевое использование компонента. Если нужен произвольный выбор значений, используйте слайдер с двумя крайними значениями. Мы не можем вводить такие функции в базовой библиотеке. Но никто не запрещает сделать кастом. Вот еще пример подобного слайдера – значения «притягиваются» к шагам
https://rsuitejs.com/components/slider/

**Comment by gh-igor** [comment]
1) почему это квалифицируется как нецелевое использование?
2) если смотреть на https://rsuitejs.com/components/slider/, то там как раз есть реализация того, о чем я прошу:
![image](https://github.com/AdmiralDS/react-ui/assets/74675573/780468a2-79ed-41ba-a464-860297e8af13)

в указанном примере есть шаг (свойство step имеется и у нас) и лейбы, и выбранное значение не прилипает

**Comment by gh-igor** [comment]
@Eldar-Gyzyev ?

**Comment by Eldar-Gyzyev** [comment]
> @Eldar-Gyzyev ?

Добрый день! Я написал вам выше, с тех пор ничего не изменилось. Мы не будем вводить эту функцию.

**Comment by gh-igor** [comment]
А возможно услышать более аргументированный ответ, почему добавление опции, расширяющей функционал компонента, а не изменяющее его, сразу квалифицируется как нецелевое использование? Почему "мы не можем вводить такие функции в базовой библиотеке"? Какие риски мы несем в этой связи? Какова цена такого изменения в дизайне (разработка уже готова)? Все-таки это требование бизнеса (клиентов), для которого, по моему мнению, это все и создается, почему в конкретном случае мы не можем удовлетворить такое требование?

**Comment by kateviditory** [comment]
Добрый день, выше уже было написано, что предложенные вами изменения не утверждены со стороны дизайна.

Наша дизайн-система реализует компоненты с общим функционалом, базовые. Узкая специализация компонентов под конкретные сценарии лежит на пользователях. Нам поступают различные запросы на расширение функционала компонентов, но мы не можем включить все возможные вариации в библиотеку. 

Рассмотрение задачи закрываю.
