### ISSUE TITLE
Некорректная ширина кнопок

### ISSUE THREAD

**Issue by postal286** [AdmiralDS/react-ui#1077]
Пустой контейнер растягивает кнопку на 4рх, при смене обычного состояния на loading-disabled ширина кнопки прыгает на эти 4рх
<img width="1339" alt="Отступ" src="https://github.com/AdmiralDS/react-ui/assets/22321648/e95b741b-38a7-4c89-863a-b03456576b86">

**Comment by kateviditory** [comment]
Добрый день! Спасибо, что завели задачу. Действительно, при переходе кнопки из обычного состояния в состояние loading происходит скачок ширины, этот момент будет исправлен.

Что касается состояния disabled, в этом случае ширина кнопки не меняется, всё отрабатывает как нужно.
