### ISSUE TITLE
Доработка сортировки в компоненте Table

### ISSUE THREAD

**Issue by victordoshenko** [AdmiralDS/react-ui#1080]
Столкнулся с такой проблемой при сортировке в компоненте Table: Сейчас в типе Column нет возможности указать тип столбца. Это приводит к необходимости писать кучу бойлерплейта в виде функции compare для каждой отдельно взятой таблицы, огромное количество лишних трудозатрат. Готовы ли рассмотреть такую доработку адмирала?: 
1/ Добавить новое поле в тип Column, содержащее информацию о типе столбца (string/date/number, и т.д.)
2/ Сделать встроенную сортировку в компоненте Table, использующую данные о типах столцов
https://admiralds.github.io/react-ui/?path=/story/admiral-2-1-data-table-table--sort-example
![image](https://github.com/AdmiralDS/react-ui/assets/19908367/41b3a2f0-7b99-441c-9637-f19c17baff50)

**Comment by kateviditory** [comment]
Добрый день! 
Ниже приведены комментарии по каждому пункту описанному вами.

1) Согласна с вами, добавление параметра type для колонки таблицы может быть полезно и позволит задавать функции сортировки, единые для разных таблиц. Мы возьмем в работу добавление параметра type для колонки и рефактор колбека onSortChange.

2) Добавление встроенной сортировки в таблицу не рассматривается, так как вся таблица построена по принципу контролируемости пользователем. Любые операции над таблицей (сортировка, выбор строк, ресайз колонок и т.д.) происходят на стороне пользователя, таблица лишь вызывает соответствующие колбеки. Менять этот принцип только для сортировки будет не рационально.
