### ISSUE TITLE
Высота контейнера для развёрнутой строки в таблице (ExpandedRowRenderer, contentMaxHeight)

### ISSUE THREAD

**Issue by Gudrodr** [AdmiralDS/react-ui#1084]
Использую таблицу из `@admiral-ds/react-ui`. Передаю контент для рендера развёрнутой строки через `expandedRowRenderer`.
Не могу переопределить размер контейнера для отображения переданного контента.

В файле /src/components/Table/Row
/RowWrapper.tsx на 116й строке указан параметр contentMaxHeight="90vh", с которым связываю данное ограничение.

Можно ли избавиться от этого ограничения или дать возможность переопределить это свойство самостоятельно?

**Comment by kateviditory** [comment]
Добрый день! Спасибо, что заметили данный момент. При разработке мы допустили ошибку, полагая, что зона детализации строки не будет превышать 90vh. Обсудив данный момент с дизайнером, пришли к решению, что зона детализации не будет ограничиваться по высоте. 

Мы уберем ограничение с contentMaxHeight и проведем рефактор компонента ExpandedRow. О том, что задача взята в разработку, вы сможете узнать, увидев, что задаче назначен определенный  milestone. Вероятнее всего задача попадет в следующий спринт.
