### ISSUE TITLE
Table - запретить Drag & Drop при нажатии на кнопку фильтров

### ISSUE THREAD

**Issue by ArtemGrinn** [AdmiralDS/react-ui#1091]
Часто бывает так, когда хочешь открыть меню фильтров, при клике на кнопку малейшее движение мышкой начинает Drag и кнопка фильтров не нажимается. Хорошо бы разделить эти функции - Drag только на заголовке, а на кнопке фильтров только клик.
![telegram-cloud-photo-size-2-5420238201043405487-x](https://github.com/AdmiralDS/react-ui/assets/2183709/28b29757-7a67-4f1f-9cc0-7eb1221fc889)

**Comment by Eldar-Gyzyev** [comment]
Мы внесем изменения, что бы DnD происходил более корректно:

«Активной для перемещения является вся площадь заголовка, но если вы «схватили» за область с иконкой (меню или сортировка), то перемещение не начнется пока курсор не выйдет за область иконки»
