### ISSUE TITLE
Некорректное поведение DropMenu/Menu при многоуровневом отображении

### ISSUE THREAD

**Issue by dark1n1996** [AdmiralDS/react-ui#1095]
При изменении активного раздела плашка сохраняет свое позиционирование, а не отображается напротив активного раздела.

![image](https://github.com/AdmiralDS/react-ui/assets/63316598/2cb41349-2bcc-45c6-8558-0703c7d37c84)

**Comment by syros** [comment]
@dark1n1996 проверил на текущей версии, указанной проблемы не наблюдается, для решения проблемы нужен пример кода или хотя бы видео воспроизведения

**Comment by dark1n1996** [comment]
С новой версией действительно починилась смена активного раздела, но при скролле плашка так и не фиксируется 

https://github.com/AdmiralDS/react-ui/assets/63316598/eb1ddee6-b951-406d-a3ed-e419d88b556f
