### ISSUE TITLE
Table - множественная группировка строк таблицы

### ISSUE THREAD

**Issue by ahito123321** [AdmiralDS/react-ui#1104]

**Comment by kateviditory** [comment]
Добрый день, уточните, пожалуйста, вам нужен функционал, который описан ниже?

<img width="855" alt="Снимок экрана 2023-09-11 в 10 27 05" src="https://github.com/AdmiralDS/react-ui/assets/23409575/d36b5027-0ca6-44d8-a43a-ec13eb83c296">

Если да, то данный функционал находится у нас в беклоге (https://github.com/AdmiralDS/react-ui/issues/1106). Он сравнительно недавно был добавлен в дизайн и пока не поступал в разработку. Конкретики по срокам реализации пока нет.

**Comment by ahito123321** [comment]
Добрый день, да, всё верно, именно такую функциональность я имел ввиду.

**Comment by kateviditory** [comment]
Закрываю данную задачу, дальнейшее наблюдение за внедрением нового функционала в таблицу можно будет осуществлять в рамках задачи https://github.com/AdmiralDS/react-ui/issues/1106.
