### ISSUE TITLE
Table - showDividerForLastColumn и пустая таблица - есть горизонтальный скролл

### ISSUE THREAD

**Issue by chebotaevroman** [AdmiralDS/react-ui#1105]
Table - showDividerForLastColumn и пустая таблица - есть горизонтальный скролл

**Comment by DrUNE** [comment]
Создайте пожалуйста минимальный пример для воспроизведения проблемы тут [https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx](https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx)

**Comment by kateviditory** [comment]
В связи с тем, что пользователь не предоставил пример для воспроизведения бага, данная задача будет закрыта.
