### ISSUE TITLE
Menu - не работает меню 3го уровня. Клик не доходит до элемента меню

### ISSUE THREAD

**Issue by taraswww777** [AdmiralDS/react-ui#1120]
Демонстрация дефекта https://youtu.be/9Wi7Zk1i3cE

**Comment by DrUNE** [comment]
Пожалуйста попробуйте сделать минимальный пример на котором можно воспроизвести поведение демонстрируемое в видео вот тут [https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx](https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx)

**Comment by Parasjona** [comment]
Для корректной работы меню необходим о использовать DropdownProvider

**Comment by taraswww777** [comment]
MenuButton + DropdownProvider помогли решить задачу 🥇
