### ISSUE TITLE
MultiSearchSelect - неправильно отображается +n 

### ISSUE THREAD

**Issue by lamtev178** [AdmiralDS/react-ui#1124]
https://github.com/AdmiralDS/react-ui/assets/71657856/a315e56c-3cfe-4e47-ae23-7d81d924031b

**Comment by syros** [comment]
@lamtev178 На какой версии это происходит? Есть ли пример, на котором стабильно воспроизводится? Проверил в версии StoryBook, не получается воспроизвести.

**Comment by syros** [comment]
@lamtev178 Проверил на примере из 120 выбранных элементов, в стандартном случае ошибки не наблюдаю. Что значит "в случае когда value добавляется вместе с options"? Value - обязательное свойство для option. Создайте пример Вашего использования на https://stackblitz.com/edit/github-ph7sgw?file=pages%2Fdocumentation%2Fselect.tsx для ускорения решения проблемы
