### ISSUE TITLE
TabMenu при изменении масштаба сбивается подчеркивание

### ISSUE THREAD

**Issue by ArtemGrinn** [AdmiralDS/react-ui#1125]
В TabMenu при изменении масштаба страницы (Ctrl + "+") выделенный пункт (подчеркивание) сбрасывается на начальный, воспроизводится в сторибуке:
![image](https://github.com/AdmiralDS/react-ui/assets/2183709/b6023f3c-5ec7-4497-9f78-0f9694d0677d)

**Comment by syros** [comment]
@ArtemGrinn На какой версии воспроизводится данная проблема? Проверил на текущей на разных браузерах и платформах, описанное поведение не приводит к ошибке. Если проблема существует в текущей версии, приложите пожалуйста видео.
