### ISSUE TITLE
Функционал а-ля tabletree

### ISSUE THREAD

**Issue by vbogachev1982** [AdmiralDS/react-ui#1129]
Подскажите , в дизайн системе планирует компонент табличного дерева , наподобие react-table-tree?
Если планируется, то  в какой перспективе?

**Comment by kateviditory** [comment]
Скорее всего вы подразумеваете функционал, описанный в данном issue https://github.com/AdmiralDS/react-ui/issues/1106. Он сравнительно недавно появился в дизайне, задача на его разработку добавлена в беклог. Конкретных данных по срокам разработки нет, из ближайших крупных задач по таблице сейчас в приоритете drag&drop строк и возможно рефакторинг таблицы с целью вынесения её в отдельную либу.

**Comment by kateviditory** [comment]
В связи с отсутствием дальнейшей активности по вопросу, закрываю задачу.
