### ISSUE TITLE
При высоком масштабе padding в Drawer принимает невалидное (негативное) значение

### ISSUE THREAD

**Issue by crutch12** [AdmiralDS/react-ui#1137]
При 67% масштабе:
![image](https://github.com/AdmiralDS/react-ui/assets/19373212/da9e3e7a-d244-449e-b0f2-b0ef61d0b540)

При 100% масштабе:
![image](https://github.com/AdmiralDS/react-ui/assets/19373212/4940fc9a-37da-402c-bfa5-92bb34f0ce06)

Воспроизвести в storybook не получилось

В первом случае padding принимает невалидное значение (паддинг не может быть отрицательным):
`padding: 8px -2px 8px 24px;`

Судя по всему этот код:
https://github.com/AdmiralDS/react-ui/blob/4ef284eac0d14aefffea65ef41f19d3dd09c1d25/src/components/Drawer/components.tsx#L23C72-L23C82

Видимо надо добавить `Math.max(0, value)`

**Comment by DrUNE** [comment]
Попробуйте сделать минимальный пример для воспроизведения тут: [https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx](https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx)
