### ISSUE TITLE
Некорректное выравнивание в компоненте <Table />

### ISSUE THREAD

**Issue by dark1n1996** [AdmiralDS/react-ui#1163]
При использовании в опции колонки поля `cellAlign?: 'left' | 'right';` выравнивается только хедер 

<img width="486" alt="image" src="https://github.com/AdmiralDS/react-ui/assets/63316598/30c9141c-cf36-4f25-81f6-93491683275c">

**Comment by kateviditory** [comment]
Добрый день, параметр cellAlign применим только к простому текстовому наполнению ячеек. Если в ячейку таблицы встроен не просто текст, а какой-то кастомный компонент со своей версткой, то пользователю нужно будет самостоятельно прописывать для этого компонента правила выравнивание контента. Насколько я могу судить по картинке, у вас как раз второй случай с кастомным наполнением ячеек.

Так как появилось недопонимание в работе параметра cellAlign, будет доработана документация в storybook и появится более детальное описание данного параметра.
