### ISSUE TITLE
[BUG] В темной теме при вставки значения из автоподсказки в текстовое поле нарушены стили

### ISSUE THREAD

**Issue by thegoncharoffs** [AdmiralDS/react-ui#1168]
![Screenshot 2023-10-30 at 16 56 51](https://github.com/AdmiralDS/react-ui/assets/29901081/a542921d-29dc-46be-b2d9-883593295e39)
Если в черной теме в текстовое поле вставлять из подсказки значение - то оно остается белым. Причем при вводе с клавиатуры - цветовая схема в порядке. 
В скриншоте приложил псевдокласс, которые переопределяет стили.

**Comment by DrUNE** [comment]
Стили браузерного агента в режиме браузерного автокомплита - посмотрим на сколько это возможно модифицировать, но есть тут баг другого рода - свойство apperance пролезло в css

**Comment by Eldar-Gyzyev** [comment]
Мы в ближайшее время проработаем этот вопрос. Отпишемся по итогам.

**Comment by Eldar-Gyzyev** [comment]
Вопрос проработали, соответствующий пункт внесли в документацию на [Инпут](https://www.figma.com/file/EGEGZsx8WhdxpmFKu8J41G/Admiral-2.1-UI-Kit?type=design&node-id=39%3A60162&mode=design&t=Ba8suYlzB42a0JWT-1).

**Comment by Parasjona** [comment]
Со стороны разработки доработка не требуется.
