### ISSUE TITLE
Проблема с отображением дефолтных данных в компоненте <Table />

### ISSUE THREAD

**Issue by dark1n1996** [AdmiralDS/react-ui#1177]
Добрый день!
При отсутствии данных в таблице (пустой массив rowList) и наличии пропа `locale={{ emptyMessage: 'Нет данных' }}` при рендере компонента эта информация не отображается (судя по всему проблема с css свойством overflow в обертке). Просьба поправить.

<img width="821" alt="image" src="https://github.com/AdmiralDS/react-ui/assets/63316598/a93b7e93-1d50-43b8-9396-da6dac6dc6c5">

**Comment by kateviditory** [comment]
Добрый день! Не удается воспроизвести описанную вами проблему. Проверяла ниже представленный код, результат рендера тоже прикладываю. 

<img width="349" alt="Снимок экрана 2023-11-15 в 13 45 13" src="https://github.com/AdmiralDS/react-ui/assets/23409575/5bcd2726-36bf-411e-83a3-c91faad8e3bd">

<img width="841" alt="Снимок экрана 2023-11-15 в 13 45 29" src="https://github.com/AdmiralDS/react-ui/assets/23409575/a2147765-bfd3-4bf8-9abf-99b000c16734">

Поэтому прошу предоставить пример кода для воспроизведения бага. Создать его можно вот здесь: https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx

**Comment by dark1n1996** [comment]
Извиняюсь, сам некорректно ограничил ширину таблицы при виртуал скроллинге, все работает корректно, спасибо.
