### ISSUE TITLE
Некорректное поведение TextButton при состоянии `disabled`

### ISSUE THREAD

**Issue by XIshArkIX** [AdmiralDS/react-ui#1184]
При навешевании слушателей `mouseenter`, `mouseleave`, `blur`, `focus` ивенты не приходят. Также при использовании `TooltipHoc` компонент не будет получать этих ивентов.

Ожидаемый результат:
В состоянии `disabled` правило **pointer-events** отсутствует или установлено в `auto`.

Фактический результат:
В состоянии `disabled` правило **pointer-events** присутствует со значением `none`.

**Comment by DrUNE** [comment]
Не работает Tooltip на задизейбленной кнопке [https://stackblitz.com/edit/github-j8tfvy?file=src%2FApp.tsx](https://stackblitz.com/edit/github-j8tfvy?file=src%2FApp.tsx)
