### ISSUE TITLE
SelectField: Проблема с ререндером Options

### ISSUE THREAD

**Issue by nysky90** [AdmiralDS/react-ui#1186]
Видео о проблеме:
https://github.com/AdmiralDS/react-ui/assets/73107181/2fbb37bc-61e3-4bd8-8151-f51dbe8f51d8
Песочница:
  https://stackblitz.com/edit/github-ha8azx?file=src%2Ftest.tsx,src%2FApp.tsx
Краткое описание проблемы в SelectField:
  Проблема заключается в зависимостях при мемоизации, когда мы делаем фильтрацию на стороне сервера нам прилетает новый массив и мы его отрисовываем в поиске, однако отображение идет предыдущих значений, а не новых. До перехода на 2.1 все работало корректно.

**Comment by syros** [comment]
Компонент работает верно, в указанном примере при рендеренге списка опций не используется атрибут key, если его добавить, то проблем не будет. Рекомендуем изучить документацию по рендеренгу списков https://react.dev/learn/rendering-lists
