### ISSUE TITLE
Table. При одновременном задании overflowMenuRender(row) и renderFilter(column) в последней колонке не отображается иконка фильтра

### ISSUE THREAD

**Issue by didolf** [AdmiralDS/react-ui#1206]
Визуально выглядит вот так:
<img width="512" alt="Снимок экрана 2023-12-13 в 23 48 12" src="https://github.com/AdmiralDS/react-ui/assets/33488113/ac656e7f-57c1-4985-89ae-cf7b4fb0117d">

Ожидается, что у последней колонки тоже будет иконка с тремя точками.

stackblitz: https://stackblitz.com/edit/github-4i5f5c?file=src%2Fexample1.tsx

**Comment by kateviditory** [comment]
Добрый день! 

Ранее в документации к таблице было прописано, что, в случае если OverflowMenu и иконки одиночных действий постоянно отображаются, то во всех строках и в заголовке появляется подложка белого цвета (чтобы визуально объединить меню и иконки одиночных действий в единый столбец). Собственно это поведение вы наблюдаете в своем примере, когда подложка перекрывает иконку фильтра в заголовке.

Спасибо, что заметили такое поведение таблицы! Совместно с нашим дизайнером функционал таблицы был пересмотрен и было принято решение, что подложка должна появляться только в строках таблицы, но не в области заголовков. Соответствующие изменения будут внесены в код.

Было:<img width="821" alt="Снимок экрана 2023-12-26 в 14 43 27" src="https://github.com/AdmiralDS/react-ui/assets/23409575/37aed7ed-f828-4e01-bbfb-78d87b190169">

Стало:
<img width="792" alt="Снимок экрана 2023-12-27 в 11 27 43" src="https://github.com/AdmiralDS/react-ui/assets/23409575/73e6b053-92dd-46cf-95a0-a95e991c44c9">

**Comment by didolf** [comment]
@kateviditory а в какую версию это попадет и когда она выйдет?
