### ISSUE TITLE
DateInput - не выходит реализовать поле с выбором только месяца года

### ISSUE THREAD

**Issue by gh-igor** [AdmiralDS/react-ui#1226]
В [дизайн-системе](https://www.figma.com/file/EGEGZsx8WhdxpmFKu8J41G/Admiral-2.1-UI-Kit?type=design&node-id=197221-20694&mode=design&t=QzqvTblGuB3mtpUG-0) в разделе DatePicker описана конфигурация компонента, позволяющая иметь поле ввода с маской `__.____` (месяц.год) с соответствующими диалогами выбора только месяца/года: 

![image](https://github.com/AdmiralDS/react-ui/assets/74675573/29e20b10-6203-49a3-83cc-36d594d670f7)

Пример из [сторибука](https://admiralds.github.io/react-ui/?path=/story/admiral-2-1-input-dateinput--date-input-pick-month) имеет ряд недостатков:

1. Маска поля ввода остается `__.__.____` вместо `__.____`
2. Невозможно выбрать год
3. После выбора месяца строка даты формируется не по маске `__.____`
4. Диалог выбора месяца в заголовке имеет название месяца и года, вместо только года

![image](https://github.com/AdmiralDS/react-ui/assets/74675573/5d325e50-4f2e-42a4-b2ba-669b86b36594)

**Comment by DrUNE** [comment]
[Пример](https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-input-dateinput--docs#dateinput--------------) будет обновлен в ближайшем релизе
