### ISSUE TITLE
Кнопки + - не работают(заблокированы) NumberInput

### ISSUE THREAD

**Issue by smff** [AdmiralDS/react-ui#1229]
"@admiral-ds/react-ui": "7.8.4",

```
<NumberInput
      value={0}
      onChange={props.onChange}
      maxValue={2000}
      readOnly={props.readOnly}
      minValue={0}
      precision={0}
      suffix=""
      dimension="s"
      placeholder="0"
    />
    ```

    При такой отрисовке кнопки + - не работают(заблокированы) 
    
    Кажется это из за того, что внутри NumberInput на 166 идет проверка if(innerValue) которая не учитывает, что 0 это допустимое число

**Comment by smff** [comment]
Я про это и говорю.  Вы это целенаправленно сделали?
![IMAGE 2024-01-29 16:21:28](https://github.com/AdmiralDS/react-ui/assets/3962132/91a5bb51-7927-4e50-a58f-81dbf47f628f)

Если innerValue проверить на 0 (как number) и с учетом всех min/maxValue - то можно получить, что пользователь может через - дойти до 0 и потом через + подняться выше.
А сейчас получается, дойдя до нуля у него блокируются кнопки и что бы продолжить пользоваться нужно руками вводить число

**Comment by DrUNE** [comment]
#1230
