### ISSUE TITLE
Перестал работать maxValue в Number Input

### ISSUE THREAD

**Issue by smff** [AdmiralDS/react-ui#1246]
"@admiral-ds/react-ui": "7.8.4",

`
<NumberInput
      value={0}
      onChange={props.onChange}
      maxValue={100}
      readOnly={props.readOnly}
      minValue={0}
      precision={0}
      suffix=""
      dimension="s"
      placeholder="0" />
      `

Ожидается:
при значениях <= 100 кнопка + активна
при значениях > 100 кнопка + не активна, и при потере фокуса введенное значение сбрасывается до 100

Реальность:
при значениях <= 100 кнопка + активна
при значениях > 100 кнопка + не активна, и при потере фокуса введенное значение НЕ  сбрасывается до 100 или сбрасывается в NaN
 
 Можно воспроизвести на:
 https://stackblitz.com/edit/github-nbz5v2?file=src%2FApp.tsx
 https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-input-numberinput--docs

**Comment by kateviditory** [comment]
<img width="1068" alt="Снимок экрана 2024-02-09 в 17 37 21" src="https://github.com/AdmiralDS/react-ui/assets/23409575/47cfd172-9fce-4e2d-b840-34bbb7433622">


Добрый день! Начиная с версии 6.0.0 в компоненте NumberInput убрана автокоррекция значения, выходящего за пределы диапазона minValue-maxValue. Теперь автокоррекция при необходимости производится на стороне пользователя.

**Comment by smff** [comment]
Понял. Спасибо. Вопрос снят!
