### ISSUE TITLE
Неправильный выбор элементов при multiple в SelectField

### ISSUE THREAD

**Issue by skankhunter** [AdmiralDS/react-ui#1256]
https://github.com/AdmiralDS/react-ui/assets/30860810/7c79afe0-9d4e-4065-82c0-787cad53206d
Выбираем чекбокс любой и если выбрать следующий выше первоначального, то выбирается все, если нажать ниже первоначального, то все сбрасывается. При нажатии на элемент внутри выпадающего списка, onChange компонента будет возвращать неверный value. На видео в консоле можно увидеть.

"@admiral-ds/react-ui": "7.1.0"

> <SelectField
>           dimension="m"
>           multiple
>           disabled={isLoading}
>           value={activeSegments}
>           onChange={(e) => onChangeGbl(e.target.value}
>           onBlur={onBlurGbl}
>           onClearIconClick={onClearSegments}
>           displayClearIcon={activeSegments.length > 0 && activeSegments[0] !== GBLParams.ALL}
>           placeholder={t('all_product_segments')}
>         >
>           {segmentsOptions}
>         </SelectField>

**Comment by DrUNE** [comment]
Приложите пожалуйста линк с минимальным примером для воспроизведения проблемы в песочнице: https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx

**Comment by skankhunter** [comment]
Создал пример, воспроизводится, как на видео
https://stackblitz.com/edit/github-pbggvl?file=src%2FApp.tsx

**Comment by skankhunter** [comment]
> Приложите пожалуйста линк с минимальным примером для воспроизведения проблемы в песочнице: https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx
Создал пример, воспроизводится, как на видео
https://stackblitz.com/edit/github-pbggvl?file=src%2FApp.tsx

**Comment by syros** [comment]
Так как компонент построен на нативном select, при использовании нативного события onchange в режиме multiple необходимо помнить, что в качестве event.target.value возвращается значение первой выбранной option из массива выбранных опций. Поэтому для обработки этого события используйте event.selectedOptions или свойство option.selected. Кроме того, рекомендуем использовать ненативное событие onSelectedChange, которое для режима multiple возвращает выбранные опции в порядке их выбора пользователем
