### ISSUE TITLE
Некорректное поведение компонента Tree

### ISSUE THREAD

**Issue by Lip-ok** [AdmiralDS/react-ui#1265]
![6e958931-b0e8-406d-be1d-855af74e533e](https://github.com/AdmiralDS/react-ui/assets/58473074/6e3230da-e835-4650-82bc-1b3c0c135818)
![0394e5ab-6ed7-4063-84b2-55f03d8617f4](https://github.com/AdmiralDS/react-ui/assets/58473074/d2e13873-3295-4fd8-ae7e-2ec5cacdeaf1)
Хотелось бы узнать по поводу компонента Tree, мне нужно получить всю ветку от родительского до дочернего компонента со значениями checked:true, но столкнулся с проблемой, что при выборе дочерних компонентов, родительские остаются в значении checked: false, но визуально отображаются как выбранные. Это баг? Или есть какая-то возможность(какой-то хендлер) получать данные от дочернего к родительскому по конкретной ветке?

**Comment by DrUNE** [comment]
Добрый день, сделайте пожалуйста минимальный пример тут (https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx) для демонстрации проблемы

**Comment by Lip-ok** [comment]
https://stackblitz.com/edit/github-i8qmmy?file=src%2FApp.tsx

Кейс в том, что чекбоксы меняются на выбраные в родителях, при нажатии на все дочерние, но родительские имеют значение false 
![Uploading Снимок экрана 2024-03-18 в 14.41.22.png…]()

**Comment by syros** [comment]
Данное поведение компонента является, багом, будет исправлено в ближайшем релизе
