### ISSUE TITLE
Проп hidden не работает для TabProps

### ISSUE THREAD

**Issue by dsnyadovskaya** [AdmiralDS/react-ui#1270]
При сете hidden в конфиге таб - таба не прячется, хотя другие (например disabled) работают.
Приходится дописывать костыли, чтобы прятать табы от условия.

**Comment by DrUNE** [comment]
Попробуйте создать пример тут https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx
это поможет разобраться в проблеме

**Comment by Parasjona** [comment]
Компонент отрисовывает все переданные в модели вкладки, для скрытия табов рекомендуется передавать в компонент только необходимые для отрисовки вкладки.
