### ISSUE TITLE
Кружок со значениями количества скрытых option's в селекте ведет себя не корректно

### ISSUE THREAD

**Issue by avorobyev174** [AdmiralDS/react-ui#1279]
Воспроизведение: нужно выбрать все значения в селекте(6 всего) и удалить 2 крайниx видимыx
Результат: осталось 4 значений - 3 видимых (1 скрыт), но кружок (+1) пропал
Ссылка на песочницу:
https://stackblitz.com/edit/github-m3zlre?file=src%2FApp.tsx

**Comment by syros** [comment]
[Запись экрана от 12.07.2024 15:08:32.webm](https://github.com/user-attachments/assets/838d541c-ee06-419c-b686-ee4d854bf6bf)

Не удается воспроизвести, возможно на определенном браузере происходит данная ошибка. Нужно больше информации для решения проблемы. Укажите тг, можем связаться там для обсуждения.
