### ISSUE TITLE
Цвет текста подсказки селекта не возможно поменять

### ISSUE THREAD

**Issue by avorobyev174** [AdmiralDS/react-ui#1280]
Цвет текста подсказки селекта не возможно поменять, если задать передать в option компонент 'T' с указанным цветом(черный). Т.е. будет черный цвет текста в подсказке на черном фоне.

Ссылка на песочницу:
https://stackblitz.com/edit/github-m3zlre?file=src%2FApp.tsx

**Comment by syros** [comment]
Данный случай не является ошибкой.

При использовании кастомных опций, реализуемых через Option children, в режиме multiple, необходимо определить у Option свойство renderChip, так как содержимое Chip и Tooltip формируется в методе renderChip, в противном случае внутри Chip и Tooltip у компонента Chip будет отображаться тот же child, что указан в качестве дочернего для Option.

Документация обновлена. Пример такой реализации можно посмотреть в "Multiple с кастомными опциями" [storybook](https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-input-select-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC-searchselect--docs)
