### ISSUE TITLE
Bug. Warning ResizeObserver при изменении ширины таблицы с динамическими ячейками.

### ISSUE THREAD

**Issue by nysky90** [AdmiralDS/react-ui#1283]
Версии библиотек:
React - 17.0.2
React-dom - 17.0.2
Admiral-ds/react-ui - 7.9.2

![image](https://github.com/AdmiralDS/react-ui/assets/73107181/f9f72362-67cb-4782-b8fc-28768c3e80f0)

Проблема: Есть таблица(компонент Table) в которой есть 3 колонки размером 33% каждая. При резком изменении размера экрана например с 1440 до 2500+ возникает warning от ResizeObserver. Если плавно тащить экран, то предупреждения не возникает. Проблему не воспроизвести в песочнице, потому что предупреждение вылезает только локально. В чате телеграмма было уже несколько сообщений по данной проблеме.

Попытки решения: Вычисление ширины таблицы в зависимости от размера экрана с нужными отступами и т.п. Работает для одной таблицы, однако требует увеличение пропсов с ростом кол-ва таблиц. Так как может быть много различных кейсов.

Предложение по решению данной проблемы: Добавить задержку при вычислении ширины таблицы в ResizeObserver в компоненте Table.

**Comment by kateviditory** [comment]
Добрый день! @nysky90, сейчас пытаюсь воспроизвести локально описанную вами проблему, но, к сожалению, пока не получается. Также использую react 17, таблицу с 3мя колонками по 33% и пытаюсь резко ресайзить экран.

Уточните, пожалуйста, в каком браузере у вас это воспроизводится. Как именно вы ресайзите экран, просто резко потянув мышью или может используйте какой-то плагин? И ещё можете привести минимальный пример верстки, в которую встраивается таблица, какие стили у родительского компонента, может какие-то дополнительные стили есть у самой таблицы. Возможно вам будет удобнее приложить видео или скрин кода.

Надеюсь, все эти уточнения помогут мне воспроизвести баг и пофиксить его.
