### ISSUE TITLE
TextInput: пересечение валидации html и валидации библиотеки 

### ISSUE THREAD

**Issue by smff** [AdmiralDS/react-ui#1295]
```
Chorme: Версия 123.0.6312.107 (Официальная сборка), (arm64)
```
```
"@admiral-ds/flags": "^3.1.1",
"@admiral-ds/fonts": "^2.0.0",
"@admiral-ds/icons": "^4.2.0",
"@admiral-ds/react-ui": "7.8.4"
```

```
<TextInput required/ >
```
Генерирует html код примерно такой

```
<input required value>
```

Получается input, который имеет атрибут **required** и пустое **value** 

При этом в css коде библиотеки находятся строки, опирающиеся на :invalid

<img width="727" alt="Снимок экрана 2024-04-08 в 13 54 08" src="https://github.com/AdmiralDS/react-ui/assets/3962132/abb88af9-6547-438d-bc18-c02739ad42fe">

При этом же в библиотеке есть строки, которые контролируют (по статусу) бордер инпута:

<img width="407" alt="Снимок экрана 2024-04-08 в 13 55 21" src="https://github.com/AdmiralDS/react-ui/assets/3962132/b9c0ba86-30c9-40aa-9b0e-573599352196">

И тут происходит самое интересное: 
css :invalid перекрывает весь прошлый контроль бордера и получается, если мы используем TextInput с required, то уже не важно какой **status** использовать оно перезатрется css

К примеру:
https://admiralds.github.io/react-ui/?path=/story/admiral-2-1-input-textinput--text-input-playground
Я руками вписал **required**
<img width="171" alt="Снимок экрана 2024-04-08 в 13 57 25" src="https://github.com/AdmiralDS/react-ui/assets/3962132/d5e73cc6-9edc-49a3-84f0-0899f720886b">

Поле моментально стало красное
<img width="463" alt="Снимок экрана 2024-04-08 в 13 57 50" src="https://github.com/AdmiralDS/react-ui/assets/3962132/6381d41c-5339-42a5-a9d2-ca976d3f03ea">

**Comment by DrUNE** [comment]
Попробуйте тут https://stackblitz.com/edit/github-7w31x6?file=src%2FApp.tsx привести пример чего вы пытаетесь добиться. Вы используете required в контролируемом режиме компонента но хотите что-бы кастомные статусы имели приоритет над браузерным?

**Comment by smff** [comment]
Вот тут пример: https://stackblitz.com/edit/github-7w31x6-jhjyhz?file=src%2FApp.tsx,package.json
версия адмирала:  "7.8.4"

В моём понимании, required не должен влиять на валидацию ... и не должен влиять на принятие решения о валидности/не валидности филда.

Опять же (в указанном примере) я специально сделал дополнительный филд, где status success, но всё равно css его :visible перекрывает.

Как таком случае делать правильно? не использовать required?

**Comment by smff** [comment]
А как узнать в какой точно версии это поправили? 
Я просто "боюсь" (на то есть причины) резко версию поднимать ... 
Где или куда можно посмотреть?

**Comment by DrUNE** [comment]
https://github.com/AdmiralDS/react-ui/releases/tag/v7.14.1
