### ISSUE TITLE
New tab Icon

### ISSUE THREAD

**Issue by KVik-N** [AdmiralDS/react-ui#1312]
Необходима иконка "Открытие в новой вкладке"

![up-right-from-square-solid](https://github.com/AdmiralDS/react-ui/assets/149819273/9d4726cb-4594-4a0e-8173-f62f47a2d6f5)

**Comment by Eldar-Gyzyev** [comment]
Сделаем в ближайшее время. В будущем с заказами пишите по адресу указанном в инструкции в дизайн-системе.

**Comment by Eldar-Gyzyev** [comment]
Готово, ищите по запросу Open in new
