### ISSUE TITLE
DateInput. Дата перескакивает на месяц назад

### ISSUE THREAD

**Issue by velkinvv** [AdmiralDS/react-ui#1330]
В последней версии адмирала появился баг с DateInput. При выборе первого дня любого месяца, дата перескакивает на первый день предыдущего месяца.
![image](https://github.com/AdmiralDS/react-ui/assets/74198246/c8463e4c-72e9-408d-aa45-3cce1f1f122b)

**Comment by DrUNE** [comment]
Не могу воспроизвести, у вас это воспроизводится в [сторибуке ?](https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-input-dateinput--docs)
