### ISSUE TITLE
Table - ширина столбца таблицы не задаётся при `name` содержащем точку.

### ISSUE THREAD

**Issue by Gudrodr** [AdmiralDS/react-ui#1343]
Если задать колонке свойство `name` с точкой в строке, то указанная ширина `width` не будет применена к столбцу целиком. Судя по девтулзам, компонентам ячеек заголовка и ячеек строк не передаётся атрибут `style`.
Предыдущая версия библиотеки, которую я использовал, была 7.12.0 и там ширина столбцов задавалась корректно. Сейчас версия 8.2.0

```
<Table
  columnList={[{
    title: 'Заголовок',
    name: 'uno.duo',
    width: '4fr',
  }]}
  rowList={[{
    uno: { duo: 'content' },
  }]}
/>
```

**Comment by kateviditory** [comment]
Добрый день!

Таблица имеет следующий API:  
- columnList - массив с объектами, описывающими колонки, где у каждой колонки должен быть name, name следует воспринимать как уникальный идентификатор, он не должен представлять из себя какую-то составную структуру с точкой
- rowList - массив с объектами, описывающими строки. В строке должно быть четкое сопоставление (маппинг): name колонки - контент ячейки в данной колонке. То есть например в вашем случае должно быть так 
`<Table
  columnList={[{
    title: 'Заголовок',
    name: 'uno',
    width: '4fr',
  }]}
  rowList={[{
    uno: 'content' 
  }]}
/>`

Если просмотреть наши примеры в сторибуке, то можно увидеть этот четкий маппинг данных. Мы также добавим дополнительное пояснение в документацию, чтобы этот момент с api стал ещё более явным. 

Если использовать приведенный вами код как есть, то у вас будет пустая ячейка, как раз потому, что в строке нет свойства с именем ‘uno.duo’. Предположу, что вы используйте колбек renderCell (из TableProps), поэтому  у вас сейчас не возникает проблем из-за неправильного маппинга. НО данный колбек устарел, сейчас нужно задавать функцию renderCell для каждой колонки отдельно (как здесь https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-data-table-table--docs#---------------------------------------rendercell--).   
<img width="1028" alt="Снимок экрана 2024-06-13 в 15 52 36" src="https://github.com/AdmiralDS/react-ui/assets/23409575/ce9303e5-a9ac-4d48-80a2-9cc930b96a06">


В рамках данной задачи код таблицы будет поправлен, так чтобы стили таблицы не ломались в случае с name, внутри которого есть точка.  НО вам нужно будет в своем проекте поправить маппинг данных в таблице и уйти от использования устаревшего колбека renderCell.
