### ISSUE TITLE
Некорректное поведение раскрывающегося меню в таблице

### ISSUE THREAD

**Issue by Nectopoo** [AdmiralDS/react-ui#1346]
Активное overflow меню, добавленное в строку таблицы  при прокрутке за пределы видимости не исчезает, а перекрывает другие элементы. 

https://github.com/AdmiralDS/react-ui/assets/62414129/f876d345-e13d-4fe5-b10b-7eccf265b6db

**Comment by kateviditory** [comment]
В ходе обсуждения с дизайнером принято решение: открытое оверфлоу меню должно закрыться, как только кнопка, открывающая меню, при скролле скрывается из области видимости тела таблицы.
