### ISSUE TITLE
ProgressPage - некорректная логика отображения `percent`

### ISSUE THREAD

**Issue by XIshArkIX** [AdmiralDS/react-ui#1379]
При `label` неравном falsy значении, `percent` скрывается. Воспроизводится в [storybook](https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-progresspage--docs).

**Comment by kateviditory** [comment]
Добрый день! Параметр percent в компоненте ProgressPage влияет только на окрашивание полосы прогресса. Обратите внимание на примеры кода для этого компонента в сторибук, в примерах видно, что если вы хотите ещё и текстовую подпись с указанием процентов, то её нужно задавать самостоятельно через параметр label.

<img width="860" alt="Снимок экрана 2024-07-05 в 10 43 27" src="https://github.com/AdmiralDS/react-ui/assets/23409575/84ca33ee-cdbf-4148-8636-3cbe6b5b7d32">

**Comment by XIshArkIX** [comment]
Как мне думается, если в компоненте есть props'ы для этого, то этим он и занимается изначально и только если нужна дополнительная функциональность, только тогда нужно расширять его функциональность. Не ожидал подвоха в том, что мне нужно расширять базовый компонент, чтобы получить базовую функциональность.

**Comment by DrUNE** [comment]
> Как мне думается, если в компоненте есть props'ы для этого, то этим он и занимается изначально и только если нужна дополнительная функциональность, только тогда нужно расширять его функциональность. Не ожидал подвоха в том, что мне нужно расширять базовый компонент, чтобы получить базовую функциональность.

ProgressPage - компонент для отображения полосы с надписью. Надпись произвольна, и зависит от бизнес задачи (количество мегабайт, остаточное время итд)

**Comment by XIshArkIX** [comment]
> > Как мне думается, если в компоненте есть props'ы для этого, то этим он и занимается изначально и только если нужна дополнительная функциональность, только тогда нужно расширять его функциональность. Не ожидал подвоха в том, что мне нужно расширять базовый компонент, чтобы получить базовую функциональность.
> 
> ProgressPage - компонент для отображения полосы **с надписью**. Надпись произвольна, и зависит от бизнес задачи (количество мегабайт, остаточное время итд)

C надписью и процентажем. Вы верно сказали, что `percent` используется для задания ширины компонента, но показывать % выполнения - это же базовая пользовательская история. Получается, что для отображения двух параметров, которые могли бы быть реализованы в адмирале, разработчикам приходится тратить человекочасы на реализацию базовой пользовательской истории.

С другой стороны, это не компонент-атом, т.е. он отображает какую-то заглушку, если пропс `label` не задан. Получается, что для простой полосы - это много, а для базовой пользовательской истории - недостаточно.
