### ISSUE TITLE
Некорректное отображение рамки при фокусе TextArea и TextField

### ISSUE THREAD

**Issue by nysky90** [AdmiralDS/react-ui#1380]
При фокусе TextArea и TextField пропадает border-radius и обратно не возвращается.

https://github.com/AdmiralDS/react-ui/assets/73107181/3b5e5e4d-882f-47e0-8b36-e92ae7eb1c8e
![image](https://github.com/AdmiralDS/react-ui/assets/73107181/f32d7b4f-8444-430c-9d9d-697c5386856e)
![image](https://github.com/AdmiralDS/react-ui/assets/73107181/4ab79b5a-1302-4143-97a0-ebbfa82ce647)
![image](https://github.com/AdmiralDS/react-ui/assets/73107181/fdfa5664-3d4e-4e91-a429-60a00a847773)

**Comment by DrUNE** [comment]
А что это за иконка в правом нижнем углу появляется?
