### ISSUE TITLE
[BUG] [Table]Нет возможности использования точки в наименовании столбцов при указании ширины.

### ISSUE THREAD

**Issue by MrNapcae** [AdmiralDS/react-ui#1382]
Нет возможности использования точки в наименовании столбцов тк css не поддерживает 
column.name с подобным наименованием test.name будет игнорироваться css тем самым ширина не будет применена к столбцу.
`  const normalColWidth = `var(--th-${column.name}-width, 100px)`;`

Баг появился в https://github.com/AdmiralDS/react-ui/commit/61828d4f7ea5dfc5ff3e0629b00cc326208181a0 .

**Comment by kateviditory** [comment]
Добрый день! Просмотрите, пожалуйста, данную задачу https://github.com/AdmiralDS/react-ui/issues/1343.
Во-первых, в рамках данной задачи пофикшено описанное вами поведение. Во-вторых, там подробно описано, что таблица не поддерживает составные имена колонок с использованием точки. От данного способа задания данных вам следует отказаться, так как это не является функционалом таблицы.
