### ISSUE TITLE
ExpandedRow content blink on render

### ISSUE THREAD

**Issue by sbjice** [AdmiralDS/react-ui#1387]
Суть бага в том что иногда в процессе рендера компонента ExpandedRowContent происходит блинк с отображением компонента, возвращаемого функцией expandedRowRender из-за особенностей рендера React.

Вот песочница с воспроизведением бага: https://stackblitz.com/edit/github-xayjbq-rxmsmx?file=README.md
В readme описал рекомендации, которые помогут устранить баг

**Comment by kateviditory** [comment]
Большое спасибо за такое подробное описание бага и предложение по его исправлению. Выпустим фикс в ближайшее время
