### ISSUE TITLE
SuggestInput - Не вставляется пробел, выбирается опция из списка

### ISSUE THREAD

**Issue by adorogov** [AdmiralDS/react-ui#1457]
Версии:
@admiral-ds/react-ui  8.16.0
react 16
styled-components 5.2.3

https://stackblitz.com/edit/github-mgaurz

На 16 реакте в SuggestInput не получается вставить пробел при открытом списке опций, выбирается первая опция в списке.
Если убрать обртку DropdownProvider, то пробел можно вставить. На 17 реакте не воспроизводится

**Comment by adorogov** [comment]
Может кто-нибудь дать комментарий? Это баг или я что-то не так делаю?

**Comment by DrUNE** [comment]
пофикшено в версии 8.21.0 https://stackblitz.com/edit/github-mgaurz-gvmt7x?file=package.json,src%2FApp.tsx,src%2Fmain.tsx
