### ISSUE TITLE
NumberInput блокируются кнопки +- при инициализации компонента

### ISSUE THREAD

**Issue by vikkond** [AdmiralDS/react-ui#1500]
При начальной инициализации компонента происходит блокировка кнопок +-
Посмотреть можно в сторибуке https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-input-numberinput--docs

происходит когда в начальное значение value ничего не передается. Если вручную ввести число - кнопки разблокируются.

**Comment by kateviditory** [comment]
Добрый день, всё верно, это заложенное в дизайне поведение компонента
<img width="721" alt="Снимок экрана 2024-09-18 в 09 35 42" src="https://github.com/user-attachments/assets/e8c88de4-0052-43d0-8a21-cf2c283bfb2b">

**Comment by vikkond** [comment]
если это поведение обусловлено дизайном, тогда стоит пробросить наверх управление disabled. Т. к. есть кейсы которые не реализуемы с таким поведением.

Например, если не задаем никакого значения по умолчанию:
1) открываются фильтры где есть поле InputNumber
2) пользователь не можем изменить значение без ввода с клавиатуры

О. Р. пользователь может вводить значение  и с клавиатуры и через кнопки +-
Ф. Р. пользователь не может вводить значение через кнопки +- и думаем, что контрол задизаблен (вообще не пользуется)


Кейс когда указали значение по умолчанию(например 0), чтобы избежать ошибочный кейс описанный выше:
1) открываются фильтры где есть поле InputNumber
2) пользователь не вводил ничего в поле InputNumber, но применяет фильтр по другому полю

О. Р. применится фильтр только по "другому полю"
Ф. Р. в применение фильтра попал и InputNumber т. к. 0 по умолчанию не отличить от 0 введеного пользователем

**Comment by DrUNE** [comment]
Инпуты по сути своей обязаны редактироваться с клавиатуры в первую очередь, кнопки + - это дополнительный элемент

**Comment by Eldar-Gyzyev** [comment]
Привет! Поправим, что бы были активными при пустом поле.

**Comment by Eldar-Gyzyev** [comment]
<img width="913" alt="image" src="https://github.com/user-attachments/assets/e3b4713f-24fa-461d-bf1d-05c3e77b48d0">

**Comment by Eldar-Gyzyev** [comment]
<img width="860" alt="image" src="https://github.com/user-attachments/assets/c5a873ba-15d7-4475-9c96-792e7284ef8a">

**Comment by DrUNE** [comment]
исправлено в 8.22.0
