### ISSUE TITLE
Проблемы при высчитывании ширины заголовка

### ISSUE THREAD

**Issue by abelgibayev** [AdmiralDS/react-ui#1530]
При использовании calc для вычисления ширины колонок есть проблема. При увеличении масштаба страницы, либо изменении размера контейнера таблицы в меньшую сторону (нужен пересчет с уменьшением ширины) в консоли появляется ошибка `ResizeObserver loop completed with undelivered notifications.`. Также, если сумма широт колонок равна 100%, то пересчет не происходит

**Comment by kateviditory** [comment]
Добрый день!

@abelgibayev Для того, чтобы взять баги в работу, нужны примеры их воспроизведения.  

Я попробовала сейчас воспроизвести как минимум 2й описанный вами баг, но проблемы с пересчетом ширины колонок не наблюдаю. Вот мой пример в песочнице https://stackblitz.com/edit/github-lkeniu?file=src%2Ftable%2Fexample1.tsx
Плюс у нас в сторибуке есть вот такой пример https://admiralds.github.io/react-ui/?path=/story/admiral-2-1-data-table-table--column-width-example, в нем как раз одна из колонок имеет ширину, заданную через calc. Пробовала менять масштаб страницы и уменьшать размер таблицы через devtools, но ошибку это не вызывает.



Поэтому создайте, пожалуйста, в песочнице (https://stackblitz.com/github/AdmiralDS/web-app-vite-admiral?file=src%2FApp.tsx) примеры воспроизведения этих двух багов на последней версии библиотеки.

**Comment by abelgibayev** [comment]
Извиняюсь за долгий ответ.
Проблема разрешилась переписыванием layout с grid на flex. Воспроизвести не удалось, но в качестве наводки могу подсказать, что использовались grid-template-rows со значениями в minmax(0, 1fr), внутри которых рендерилась таблица.
Сейчас всё в порядке, спасибо за пример!

**Comment by kateviditory** [comment]
Спасибо за ответ, рада, что ваша проблема разрешилась! Так как воспроизвести баг на данный момент не удалось (в том числе при оборачивании таблицы в контейнер с grid-template-rows), задачу закрываю
