### ISSUE TITLE
Поисковая строка в мультиселекте

### ISSUE THREAD

**Issue by flerko** [AdmiralDS/react-ui#1550]
Добрый день

https://admiralds.github.io/react-ui/?path=/story/admiral-2-1-form-field-selectfield--custom-option-multi-search-select

При поиске в множественном селекте, выпадает новый список найденных опшнов.
Если выбрать что-то одно, из найденного, то введенное в инпут значение стирается, и список запрашивается заново.
Нужно снова вбивать значение для поиска.

**Comment by Eldar-Gyzyev** [comment]
Мы провели исследование. Такое поведение, как сейчас в Адмирале, встречается в подавляющем большинстве дизайн-систем. По факту, мы нашли описываемое вами поведение только в одной ДС Consta. Если получится реализовать ваш вариант как альтернативный, без ущерба основному, то сделаем.

**Comment by flerko** [comment]
> Мы провели исследование. Такое поведение, как сейчас в Адмирале, встречается в подавляющем большинстве дизайн-систем. По факту, мы нашли описываемое вами поведение только в одной ДС Consta. Если получится реализовать ваш вариант как альтернативный, без ущерба основному, то сделаем.

Можно ли реализовать так, чтобы поведение компонента не изменилось, но дать управление пропсом для поисковой строки?

1) Либо просто булеан переменную, которая отвечает за то, надо ли очищать поисковую строку после выбора элемента
2) Либо дать полное управление поисковой строкой
