### ISSUE TITLE
Некорректное отображения действий в таблице при наличии скролла

### ISSUE THREAD

**Issue by dev-geyer** [AdmiralDS/react-ui#1551]
Для воспроизведения бага необходимо прокинуть пропы showRowsActions, greyZebraRows, добавить компонент действий с помощью поля overflowMenuRender и поместить таблицу в контейнер, который по ширине меньше суммарной ширины всех колонок в таблицы (чтобы появился скролл). Дальше проскроллить влево, чтобы компонент действий оказался над соседними колонками.
<img width="214" alt="image" src="https://github.com/user-attachments/assets/25df7d7f-1a52-4f23-99ec-cc96562e4f40">
<img width="402" alt="image" src="https://github.com/user-attachments/assets/71f882f7-134c-4b85-8a3b-0c8d8ea2a154">

**Comment by kateviditory** [comment]
В связи с отсутствием дальнейшей активности задача закрывается
