### ISSUE TITLE
Утечка памяти в таблице

### ISSUE THREAD

**Issue by AleksandrKornev** [AdmiralDS/react-ui#1567]
Добрый день!

https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-data-table-table--docs

В компоненте таблицы выявил утечку памяти, конечная логика воспроизведения не понятна, но если к текущему массиву данных добавляется новая строка/строки, то начинает течь память

Репозиторий для воспроизведения - https://github.com/AleksandrKornev/admiral-table-issue
Генерируется массив (кол-во элементов 201), в рандомном порядке берется 200 элементов, чтобы была эмуляция нашего кейса, когда добавляется один новый элемент, а последний убирается из этого списка
По сравнению с реальным использованием, в тестовом примере память не так сильно течет, но в нашем случае мы в течении большого периода времени можем уйти в OOM

**Если пробрасывать одни и те же 200 элементов (в одинаковом/разном порядке), то память утекает медленно (если вообще утекает)**

Шаги:
1. Загружается страница
2. Нажимаем запуск
3. Ждем 2 тиков и останавливаем
4. Делаем снапшот
5. Повторяем 2-4 шаги, но увеличиваем кол-во тиков для ожидания

Также прикладываю запись снапшотов

https://github.com/user-attachments/assets/624e9369-3c7a-4e3a-af2b-18ae812d211c

**Comment by DrUNE** [comment]
Пока не получается воспроизвести пример так что-бы были явные утечки памяти. После 4х часов непрерывной работы по памяти не замечено отклонение в сторону увеличения не собираемого мусора свободных объектов. графики памяти и активности стабильные "пила" и повторяющиеся ступеньки

**Comment by AleksandrKornev** [comment]
Хорошо, чтобы было более наглядно и объективно, и в сравнении, сделал 3 снапшота для таблицы Admiral, и для таблицы Material UI

Каждый замер выполняется в новой вкладке, в инкогнито (чтобы расширения не аффектили вкладку по памяти)
Запускаю перетасовку, жду определенное время (ниже), останавливаю (чтобы была четкая цифра о размере куче) и делаю снапшот после нескольких нажатий на collect garbage (вычищает все, остается только то, что не может быть освобождено)

1 снапшот - спустя минуту (минута сессии)
2 снапшот - спустя 2 минуты (3 минуты сессии)
3 снапшот - спустя минуту (5 минут сессии)

![image](https://github.com/user-attachments/assets/48e197fa-47a8-4226-b9cf-39c5809c7e01)
Замер для таблицы Material UI

![image](https://github.com/user-attachments/assets/e9c554f2-9126-4af5-800a-65e5170727b4)
Замер для таблицы Admiral

Как видим, в Material UI память остается относительно стабильной, сравнивая 1 и 3 снапшоты и смотря на дельту, все уходит на V8, за исключением  Array, Object, но и там крайне малые значения
Если же мы посмотрим на замер Admiral, то кол-во не высвобождаемой памяти растет, дельта для Array, Object растет

**Comment by DrUNE** [comment]
Так-же "относительно стабильной" здесь можно назвать и память у таблицы адмирала, на моем скриншоте за 4 часа работы не произошло увеличение неснижаемого занятого объема, по этому сколько бы ваш пример ни работал это не приведет к аварийной остановке по причине нехватки памяти.

**Comment by DrUNE** [comment]
Я запустил ваш обновленный пример еще раз:
- Для начала рефреш страницы, запуск изменений на минуту, останов,  очистка памяти. Мы видим 116мб. Можем предположить, что это начальный объем не снижаемой памяти
![tg_image_4233793768](https://github.com/user-attachments/assets/de92b38d-458c-4216-8420-e3428acdefd4)
- Запуск на 20минут, после чего видим 330мб
![tg_image_3369550264](https://github.com/user-attachments/assets/300968d7-d4ef-4d31-a87f-e217cae8a66e)
- Останов и очистка памяти, видим 162мб
![tg_image_1392809200](https://github.com/user-attachments/assets/154be017-ead2-410a-bc05-b6fd47699c72)
Тоесть можно предположить, что линейный рост памяти за 20 минут составил около 45мб, и если мы запустим и продолжим еще на 20 минут то памяти должно быть занято не меньше 200мб.
- Продолжим и запускаем на следующие 20 минут, при работе видим пик в 350мб
![tg_image_785292374](https://github.com/user-attachments/assets/94032b32-0c89-400a-b533-e81c68fe880b)
- Останавливаем и очищаем, и видим 161мб
![tg_image_372156871](https://github.com/user-attachments/assets/e9e01090-b9d1-49e4-9075-918737184bfe)
Вывод:
 За последующие 20 минут не произошло ни какого прироста, ни по листенерам ни по дом нодам ни по памяти, а ожидался линейный прирост минимум на 45мб. Инструменты, записывающие снапшоты записывают всю активность, включая активность открытого сокета на дев сервер слушающего обновления кода для хот релоада, открытых дев тулс в браузере, возможно с включенными логерами сетевой активности или консоли. По этому снапшоты в данном случае не дают ни какой информации которую можно было-бы в точности воспроизвести или добиться того что-бы снапшоты "выглядели хорошо". Тем не менее пример в котором данная версия таблицы крашит браузер был бы и тестовым примером для проверки пофикшено ли что-то или нет в таблице, без такого примера вносить изменения и смотреть снапшоты считаю бессмысленным, так как достоверности того что у вас таблица не крашнется все равно не будет.

**Comment by DrUNE** [comment]
> То есть это нормальное явление, что разница в 0мб (для MUI) и 20мб (для Admiral) за один и тот же период?

Да, считаю нормально.

**Comment by DrUNE** [comment]
Закрываю по причине отсутствия активности

**Comment by AleksandrKornev** [comment]
Спустя столько времени отпишу на всякий случай, мб у кого-то такая же проблема возникнет
Проблема была не в таблице, дело было в React, а именно что React кэширует ключи (key) для списков, но в нем нет механизма для их удаления, если рендер таблицы построен как очередь (каждый рендер пропадает старая строка и новая добавляется), то DOM ноды по ключу копятся в памяти
