### ISSUE TITLE
Типизация ModalContent

### ISSUE THREAD

**Issue by flerko** [AdmiralDS/react-ui#1583]
Версия адмирала: 8.28.0
Мигрирована с 8.25.1, на ней ошибки нет

import { ModalContent } from '@admiral-ds/react-ui';

![image](https://github.com/user-attachments/assets/f0949ee1-834b-4496-839c-4a22c9bebdfb)

Типизация children отвалилась, покрыли игнором на данный момент

![image](https://github.com/user-attachments/assets/d1d246e4-e60b-4e21-85f3-1241bce0b6c7)

**Comment by DrUNE** [comment]
При билде какую ошибку выдает typescript ?
Попробуйте перезайти в VSCode

**Comment by flerko** [comment]
> Какой версии typescript и @types/react в проекте? При билде какую ошибку выдает typescript ? Попробуйте перезайти в VSCode

"typescript": "^4.5.5",
"@types/react": "^17.0.40",

Билд:
TS2322: Type '{ children: ReactNode[]; id: string; "data-test-id": string; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'children' does not exist on type 'IntrinsicAttributes'.                                                           
    94 |         {title}
    95 |       </ModalTitle>
  > 96 |       <ModalContent id='modal-content' data-test-id='confirmation-dialog-text'>
       |        ^^^^^^^^^^^^
    97 |         {text}
    98 |         {extraText}
    99 |       </ModalContent>

**Comment by DrUNE** [comment]
> > Какой версии typescript и @types/react в проекте? При билде какую ошибку выдает typescript ? Попробуйте перезайти в VSCode
> 
> "typescript": "^4.5.5", "@types/react": "^17.0.40",
> 
> Билд:
> 
> ```
> TS2322: Type '{ children: ReactNode[]; id: string; "data-test-id": string; }' is not assignable to type 'IntrinsicAttributes'.
>   Property 'children' does not exist on type 'IntrinsicAttributes'.                                                           
>     94 |         {title}
>     95 |       </ModalTitle>
>   > 96 |       <ModalContent id='modal-content' data-test-id='confirmation-dialog-text'>
>        |        ^^^^^^^^^^^^
>     97 |         {text}
>     98 |         {extraText}
>     99 |       </ModalContent>
> ```

интересует что выдает ```npm ls typescript @types/react```

**Comment by flerko** [comment]
> интересует что выдает `npm ls typescript @types/react`

```
+-- @commitlint/cli@16.2.1
| `-- @commitlint/load@16.2.1
|   +-- cosmiconfig-typescript-loader@1.0.5
|   | `-- typescript@4.5.5 deduped
|   `-- @types/react-redux@7.1.22
|     `-- @types/react@17.0.40 deduped
+-- eslint-plugin-custom-rules@1.0.4 -> .\eslint-plugin-custom-rules
| +-- @typescript-eslint/eslint-plugin@8.4.0
| | `-- ts-api-utils@1.3.0
| |   `-- typescript@4.5.5 deduped
| `-- typescript@4.5.5 deduped
+-- fork-ts-checker-webpack-plugin@6.5.3
| `-- typescript@4.5.5 deduped
+-- html-react-parser@5.1.18
| `-- @types/react@17.0.40 deduped
+-- react-scripts@5.0.0
| `-- typescript@4.5.5 deduped
+-- swagger-typescript-api@13.0.3
| `-- typescript@5.1.6
+-- ts-node@10.5.0
| `-- typescript@4.5.5 deduped
+-- typescript-plugin-css-modules@3.4.0
| `-- typescript@4.5.5 deduped
`-- typescript@4.5.5
```
