### ISSUE TITLE
Ошибка типов при использовании TooltipHoc в React 16

### ISSUE THREAD

**Issue by adorogov** [AdmiralDS/react-ui#1602]
@admiral-ds/react-ui 8.29.0
react 16.14.0

https://stackblitz.com/edit/github-mgaurz-rhnmfqrz?file=src%2FApp.tsx

'ButtonWithTooltip' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.(2786)

**Comment by DrUNE** [comment]
Поправим в ближайшем релизе. Сделал пример как это можно обойти, исправил импорт иконки и добавил типизацию для styled-components https://stackblitz.com/edit/github-mgaurz-4qymrppu?file=src%2FApp.tsx,package.json

**Comment by DrUNE** [comment]
fixed https://stackblitz.com/edit/github-mgaurz-fxq4an6r?file=src%2FApp.tsx
