### ISSUE TITLE
Refactor - Storybook - Checkbox

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#228]
не показаны:

- [x] чекбокс с информером,
- [x] адишанал текст,
- [x] в 2 строки,
- [x] со звездочкой обязательно 

https://www.figma.com/file/NOQTMNuZ6i5ov9az0P4NNL/%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2?node-id=7%3A2

**Comment by Parasjona** [comment]
Чекбоксы с информером и дополнительным текстом показаны в сторибуке в разделе FormField/CheckboxField
Туда же добавила вариант в две строки
