### ISSUE TITLE
Refactor - Storybook - Dropdown menu

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#233]
Добавить примеры:
- [x] чекбокс/радио
- [x] длинный текст

https://www.figma.com/file/NOQTMNuZ6i5ov9az0P4NNL/%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2?node-id=17%3A30

**Comment by Parasjona** [comment]
Пример с категориями в сторибуке есть
