### ISSUE TITLE
Refactor - Storybook - Suggest Input

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#234]
не совсем верно работает вот эта функция. просто открывает все варианты, если нет совпадений,
вместо того, чтобы писать нет совпадений 

https://www.figma.com/file/NOQTMNuZ6i5ov9az0P4NNL/%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2?node-id=20%3A35

**Comment by Parasjona** [comment]
SuggestInput не должен ничего фильтровать в выпадающих пунктах, так как порядок того, что там должно находиться, и содержание полностью зависит от того, кто управляет компонентом. При получении пустого массива опций, компонент выдаст сообщение "Нет совпадений".
Добавила примеры в сторибук
