### ISSUE TITLE
Refactor - Storybook - Notification 

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#235]
https://www.figma.com/file/NOQTMNuZ6i5ov9az0P4NNL/%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2?node-id=21%3A44

**Comment by Parasjona** [comment]
1. Нельзя выключить ссылку в настройках (можно в текстовом поле, убирается если стереть текст) - правильное поведение, если есть текст ссылки, то она отображается, если нет, то не отображается
2. Нет настроек Toast Notifications - настраивать можно стандартные варианты места всплытия position и autoDeleteTime
3. Не нашла лайн - добавила пример в сторибук
4. Открываются в одном месте (несмотря на изменение настроек) - настраивать стандартные варианты места всплытия можно в базовом примере
