### ISSUE TITLE
Feature - Table - add drag and drop

### ISSUE THREAD

**Issue by Parasjona** [AdmiralDS/react-ui#262]
В документацию на Data Table добавлено описание Drag and Drop строк и столбцов

![image](https://user-images.githubusercontent.com/57989925/182333161-eb5c6811-ed09-49a7-ab70-1ebbfc381b0a.png)

В таблицы добавлена функция перетаскивания строк между группами строк, в том числе перемещением на заголовок группы

**Comment by kateviditory** [comment]
В рамках данной задачи реализован drag&drop колонок таблицы. Для drag&drop строк заведена другая задача https://github.com/AdmiralDS/react-ui/issues/947
