### ISSUE TITLE
Field - расположение Label 

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#268]

**Comment by magstrong07** [comment]
На положение лейбла стали влиять свойства обёртки:
Было:
![image](https://user-images.githubusercontent.com/98021358/182350681-b5ae021c-5a3e-4bc7-920e-a5f2e58d1168.png)

Стало:
![image](https://user-images.githubusercontent.com/98021358/182350762-3c880139-3d71-441f-938f-07283ce71f53.png)

По дизайну label должен быть слева. 

![image](https://user-images.githubusercontent.com/98021358/182351129-47750b19-4289-44c1-addb-637e8ed8130f.png)


![image](https://user-images.githubusercontent.com/98021358/182350988-1100b9e1-d7de-437f-8d25-78e6e12e74d5.png)
