### ISSUE TITLE
Bug - SearchSelect - ClearIcon

### ISSUE THREAD

**Issue by vk164** [AdmiralDS/react-ui#275]
Некорректное поведение при очистке компонента SearchSelect. Выбранное значение остается в поле после очистки
Видео: 

https://user-images.githubusercontent.com/27344004/183371254-28d730bd-5558-486a-abc7-9e89368b98bc.mov

**Comment by DrUNE** [comment]
Не удалось воспроизвести на [сторибуке](https://admiralds.github.io/react-ui/?path=/story/admiral-2-1-form-field-selectfield--simple-search-select-story&args=displayClearIcon:true) может неверно отрабатывает логика стейт менеджера формы? Необходимо больше деталей
