### ISSUE TITLE
Bug - DateRangeInput - При ручном вводе начальная дата может быть больше конечной

### ISSUE THREAD

**Issue by vk164** [AdmiralDS/react-ui#276]
При заполнении DateRangeInput от руки возможен вариант, когда начальная дата больше финальной. 

Пример: 05.08.2023 - 07.08.2022

**Comment by DrUNE** [comment]
Валидация введеных вручную значений происходит на стороне разработчика форм и используемых в проекте библиотек работы с формами, компонент контролирует только маску (формат) текстового поля
