### ISSUE TITLE
Bug - SearchSelect - ClearIcon Accessibility

### ISSUE THREAD

**Issue by vk164** [AdmiralDS/react-ui#278]
При работе с клавиатуры невозможно перейти к значку "очистить поле" для полей с выпадающим списком. 

По табу переход на поле, через Enter открыть список, выбрать значения и дальше значения можно только удалять по одному через Backspace, невозможно перейти на иконку крестика, очищающее поле целиком.

**Comment by DrUNE** [comment]
Какое поведение вы предлагаете?

**Comment by vk164** [comment]
При навигации через tab осуществлять переход к иконке очистки также, как в DateInput к иконке календаря

**Comment by syros** [comment]
В дизайн-системе в качестве стандарта принято поведение нативных контролов - иконки внутри input не имеют собственного фокуса. Таким образом, навигация через tab осуществляется между полями ввода. Поведение всех компонентов типа input будет приведено к стандартному.
