### ISSUE TITLE
Feature - SearchSelect - LoadingIndicator

### ISSUE THREAD

**Issue by vk164** [AdmiralDS/react-ui#279]
Добавить возможность отображать loadingIncdicator для SearchSelect.
Макет:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/27344004/183373724-8d456496-5cd4-43e7-8e15-c3e2a10021e9.png">

**Comment by DrUNE** [comment]
Дополнительно необходимо изменить логику и отображения статуса загрузки в компоненте SuggestInput  для единообразия
