### ISSUE TITLE
[Bug]: скачут выпадающие списки, если не хватает места до нижней границы экрана

### ISSUE THREAD

**Issue by Soul1** [AdmiralDS/react-ui#285]
Видео с проблемой доступно здесь: [video](https://www.awesomescreenshot.com/video/10361359?key=230b586c0d0d567b0d65cdf79fe3c329)

 

Выпадающий список должен сразу открывается в нужную сторону в зависимости от расстояния до границы экрана

**Comment by DrUNE** [comment]
В выпадающем списке может находиться контент произвольной высоты, который не известен до рендеринга, дополнительно после рендеринга страница может скроллится или изменяться в размерах по этому положение постоянно пересчитывается с определенным интервалом и список по умолчанию всегда открывается сначала вниз

**Comment by Soul1** [comment]
> В выпадающем списке может находиться контент произвольной высоты, который не известен до рендеринга, дополнительно после рендеринга страница может скроллится или изменяться в размерах по этому положение постоянно пересчитывается с определенным интервалом и список по умолчанию всегда открывается сначала вниз

Можно ли рассчитывать положение при первом открытии? На видео видно, что при первом открытии список не влезает в экран.

**Comment by kateviditory** [comment]
Пришли к такому решению. При начальном рендере дропдаун отрисовывается снизу с opacity=0. В течение 200ms значение opacity сменится с 0 на 1, за это время произойдет вычисление размеров дропдауна и его правильное позиционирование. За счет этого визуально для пользователя не будет виден скачок выпадающего списка. Кроме того, позиция дропдауна постоянно будет пересчитываться с определенным интервалом

**Comment by SQReder** [comment]
@kateviditory Почему  не использовать useLayoutEffect, который происходит после рендера и не померить размер контента?
Эта задержка в 200ms очень раздражает

**Comment by kateviditory** [comment]
@SQReder, здравствуйте!

Задержка в появлении дропдауна позволяет избежать ошибок при первоначальном рендере компонента.

1. Кейс с загрузкой шрифтов: если пользователь перезагрузит страницу, это вызовет загрузку шрифтов, которая занимает некоторое время. По завершении загрузки шрифтов размер дропдауна может измениться, что приведет к пересчету позиции и возможным прыжкам. Небольшой задержки в появлении обычно хватает для подзагрузки шрифтов и пересчета размера и позиции дропдауна

2. Дропдаун рендерится внутри компонента PositionInPortal - это компонент-обёртка, позволяющий рендерить дропдаун в любом месте в DOM. Компонент PositionInPortal изначально рендерится безразмерным, а затем адаптирует свой размер под targetElement. Это в свою очередь также может привести к изменениям в размере дропдауна. Небольшая задержка в начале позволяет скрыть пересчеты и прыжки дропдауна

Поэтому использования одного useLayoutEffect в случае с нашим компонентом будет недостаточно. 

P.S. Работа по данной задаче завершена 2 года назад, поэтому если будут ещё возникать вопросы по компоненту, лучше заводить новую задачу.

**Comment by SQReder** [comment]
> 1. По завершении загрузки шрифтов размер дропдауна может измениться

Серьёзно? Это реально частый кейс, на который вы ориентируетесь?

Откройте для себя https://floating-ui.com, пожалуйста. Зачем велосипедить порталирование и расположение? Не хотите использовать внешнюю библиотеку? Ну _вдохновитесь_ хотябы и уберите костыли
