### ISSUE TITLE
Select - селект не очищается с клавиатуры

### ISSUE THREAD

**Issue by Soul1** [AdmiralDS/react-ui#365]
если выбран опшен в селекте, то нельзя удалить с клавиатуры выбранное значение, ни по нажатию кнопки "Del", ни по 
 "Backspace", последний просто стирает значение, но как только убираем фокус с поля, то стертое значение возвращается.
 Можно ли сделать очищение селекта с клавиатуры?

**Comment by syros** [comment]
Такая доработка не планируется. Данное поведение не соответствует ни нативным html элементам, ни дизайн-системе.
