### ISSUE TITLE
Поддержка module federation

### ISSUE THREAD

**Issue by vyachsed** [AdmiralDS/react-ui#411]
Библиотека перестала работать с module federation после добавления "title": "module" в package.json
Возможно, дело не совсем в библиотеке, а настройке самого module federation, но я предлагаю сделать такой хотфикс: https://github.com/AdmiralDS/react-ui/pull/410
И уже потом разбираться, в чем истинный баг и как его можно не допустить иными, более правильными способами
Это никак не повлияет на работу библиотеки, а у всех наших команд, разрабатывающих микрофронтенды, снова начнет работать библиотека
Аналогичный баг и пример для воспроизведения: https://github.com/module-federation/module-federation-examples/issues/1962

**Comment by DrUNE** [comment]
Согласен временно внести изменения, похоже дело в лоадерах вебпака которые неверно воспринимают файлы пакета с расширениями .cjs  или .mjs [(хотя должны и на это существует стандарт )](https://nodejs.org/api/packages.html#determining-module-system)
