### ISSUE TITLE
Notification, Toast - проблема ссылок

### ISSUE THREAD

**Issue by kateviditory** [AdmiralDS/react-ui#481]
Есть следующая проблема с ссылками
Компонент Notification и Toast соответственно (мб есть и другие) принимают linkText и href
Нам такой вариант не подходит: вы используете свой Link, который по факту голый тег <a>, а у нас на проекте используется react router

Не хочется ни рассчитывать ссылку доставая из контекста basename (пусть этим занимается react router) ни получать перезагрузку страницы при переходе по ссылке, и вообще было бы круто самим контролировать поведение ссылки: с релоадом, с открытием в новой вкладке, изменение адресной строки в рамках SPA

Предлагаю рассмотреть возможность пробрасывать свой Component, либо добавить возможность пробрасывать element

Мы причем используем не напрямую react router, а свою собственную обертку, чтобы клёво организовать микрофронтенды
Нужно иметь в виду, что компонент реально может быть любой

**Comment by kateviditory** [comment]
Доработан компонент Link (https://github.com/AdmiralDS/react-ui/pull/650): 
- добавлен параметр as, позволяющий рендерить любой html элемент или компонент в качестве root-элемента
- добавлен LinkComponentCssMixin - миксин со стилями компонента Link, который можно применять к своим кастомным компонентам

**Comment by DrUNE** [comment]
Добавлена возможность рендерить нотификацию с полностью кастомным наполнением
