### ISSUE TITLE
TabMenu - проработать возможность перехода на render-проп модель

### ISSUE THREAD

**Issue by kateviditory** [AdmiralDS/react-ui#593]
Попробовать унифицировать подход к рендерингу списка чего бы то ни было внутри контейнера имеющего стейт.
И сделать везде так, как сделано в Menu, добавив render пропсу в модель.

**Comment by Parasjona** [comment]
Сделано в рамках задачи по рефактору TabMenu
https://github.com/AdmiralDS/react-ui/issues/1339
