### ISSUE TITLE
Пропадает выделение табов при зуме на старых версиях Chrome и Yandex browser 

### ISSUE THREAD

**Issue by aTarasov89** [AdmiralDS/react-ui#602]
При зуме браузера пропадает выделение текущего таба и не появляется при выборе другого таба.
Также если табов в строке много часть из них просто пропадает. 

Воспроизводится при настройках масштаба дисплея в windows - 100%.  

![image](https://user-images.githubusercontent.com/28714925/212881508-d4a128a3-ffa1-4bbd-88f4-a0d47445ef4d.png)

Версия библиотеки:   3.10.1
Версия Chrome: 91.0.4472.106
Версия Yandex:  20.8.0.903

![табы_1](https://user-images.githubusercontent.com/28714925/212880713-50effbd1-c32e-44b9-a9c6-5bd8a274dc76.gif)
![табы_2](https://user-images.githubusercontent.com/28714925/212880760-8be6c3d0-bfed-44e1-b7d6-285a7668a11d.gif)

Изучение кода привело в https://github.com/AdmiralDS/react-ui/blob/95d384737b6a7c2f71e44ae0b26be937720a6078/src/components/TabMenu/index.tsx#L253 

При воспроизведении бага intersectionRatio равен 0.9961674809455872 а не 1.0

**Comment by dariawish** [comment]
Старые версии браузеров не поддерживаем, попробуйте воспроизвести в 2х последних мажорных версиях
@syros рассмотрит в 2022.1.3

**Comment by syros** [comment]
Исправлено в #722
