### ISSUE TITLE
Запрос на изменение правила отображения иконки

### ISSUE THREAD

**Issue by merioara-denis** [AdmiralDS/react-ui#615]
`src/components/Tag/index.tsx:300`

```tsx
{statusViaBackground && icon && <Icon>{icon}</Icon>}
```

Прошу тут убрать (statusViaBackground ) в правели, отображение статуса фоном может требоваться параллельно с отображением иконки

![image](https://user-images.githubusercontent.com/88931298/214065265-3a9d7acc-6c4e-45d4-9e89-c25fde283483.png)

**Comment by Parasjona** [comment]
В дизайне иконка может появляться только при условии отображения статуса фоном
![image](https://user-images.githubusercontent.com/57989925/214069641-c0888ed5-e78c-4d32-8a1e-eb8425f0583c.png)
Так что эта проверка существует для того, чтобы иконка не появлялась в случае с цветной статусной меткой
![image](https://user-images.githubusercontent.com/57989925/214069577-e94400b7-6245-4f9e-88d8-f73e1d84ad7f.png)

**Comment by Parasjona** [comment]
Пример реализации можно увидеть здесь:
https://admiralds.github.io/react-ui/?path=/story/admiral-2-1-tag--tag-icon
