### ISSUE TITLE
Margin на компоненте Tag

### ISSUE THREAD

**Issue by misusimusasi** [AdmiralDS/react-ui#624]
Внешний отступ на компоненте Tag полностью убивает смысл в атомарности компонента. Так как предполагается, что он может использоваться в любом месте интерфейса, то не понятно, зачем ему что-то от себя двигать.

Исправить это своими силами без костылей, типа important в css не представляется возможным, т.к. из-за особенности styled-components невозможно накладывать стили и одновременно прокидывать пропс "as" во внутрь.

**Comment by DrUNE** [comment]
> Внешний отступ на компоненте Tag полностью убивает смысл в атомарности компонента. Так как предполагается, что он может использоваться в любом месте интерфейса, то не понятно, зачем ему что-то от себя двигать.
> 
Согласен, у компонента не должно быть предустановленных внешних отступов.

> Исправить это своими силами без костылей, типа important в css не представляется возможным, т.к. из-за особенности styled-components невозможно накладывать стили и одновременно прокидывать пропс "as" во внутрь.
>
Это не верное утверждение 
https://stackblitz.com/edit/github-z4zcmz?file=pages/documentation/select.tsx

**Comment by misusimusasi** [comment]
Но при этом теряются стили или это только у меня в браузере такое поведение
<img width="1236" alt="Screenshot 2023-01-27 at 16 48 49" src="https://user-images.githubusercontent.com/27222553/215102348-11848982-eb41-4b56-9c18-0db81c8e1d00.png">

**Comment by DrUNE** [comment]
> Но при этом теряются стили или это только у меня в браузере такое поведение <img alt="Screenshot 2023-01-27 at 16 48 49" width="1236" src="https://user-images.githubusercontent.com/27222553/215102348-11848982-eb41-4b56-9c18-0db81c8e1d00.png">

Для сохранения стилей после обертки используется другая пропса : 
https://styled-components.com/docs/api#forwardedas-prop
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/843964/215160727-a827c8b6-4c33-41cf-b812-654335e10aba.png">
