### ISSUE TITLE
Performance - Event Loop - observeReact

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#737]
Event Loop - observeRect – кривая функция на которой базируются все выпадающие списки, либо перерасчитывающиеся по измерениям компоненты, завязка на глобальную переменную

**Comment by DrUNE** [comment]
Необходимо больше конкретной информации и возможность продемонстрировать проблему для поиска решения и дальнейшей уверенности, что проблема решена после внесения изменений.

**Comment by vyachsed** [comment]
@vyachsed

**Comment by DrUNE** [comment]
Были внесены изменения в observeRect в связи с проблемой при обозрении дом ноды несколькими клиентами одновременно. Возможно это сказалось и на перфомансе и где-то стало лучше, а где-то стало хуже. Закрываю эту задачу из-за отсутствия стенда способного продемонстрировать проблему
