### ISSUE TITLE
Breadcrumbs - ошибки в синтаксисе используемых тэгов 

### ISSUE THREAD

**Issue by Crash1234567** [AdmiralDS/react-ui#742]
1) В nav вместо ссылок используются другие элементы
2) В ol, помимо li, используются другие элементы
3) li используется без родительского ol
4) Лишний div (data-number="3"). В Items был передан массив из 3-х элементов (т.е. data-number должен быть от 0 до 2)

Предложения для исправления: 
- указывать корректный синтаксис для тэгов ([nav](http://htmlbook.ru/index.php/html/nav) [ol](http://htmlbook.ru/html/ol))
- сверстать все на div
- убрать лишний div (data-number="3")

![Breadcrumbs](https://user-images.githubusercontent.com/94962270/225949172-c4878155-c5cd-4ea9-a546-c0693755f65f.png)

**Comment by kateviditory** [comment]
Добрый день, пункты 2-3 будут исправлены. Спасибо, вы верно заметили, что элемент ol может содержать только элементы типа li.
Пункт 1 - элемент nav содержит в себе элементы ссылок (a), но с определенным уровнем вложенности.
Пункт 4 - div, о котором идёт речь не является лишним в компоненте и удален не будет. Он необходим для правильного выравнивания хлебных крошек. Для него будет добавлен атрибут aria-hidden, и мы рассмотрим возможность не задавать ему атрибут data-number.
