### ISSUE TITLE
Документация - Input

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#746]
https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-form-field-inputexfield--input-ex-field-input 
* 		- PrefixValueList - добавить контрол 
* 		- SuffixValueList - добавить контрол

**Comment by Parasjona** [comment]
В данных примерах не предусмотрено изменение данных props, поэтому контролы для них отключены.
Примеры использования можно посмотреть в коде.
