### ISSUE TITLE
Документация - multiButton 

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#759]
https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-multibutton--multi-button-appearance 
* 		- Options - добавить description 
* 		
* 		- Active - изменить контрол на стринг 
* 		
* 		- DisableSelectedOptionHighlight - изменить контрол на булеан 
* 		
* 		- isVisible  - не объект - изменить контрол на булеан

**Comment by syros** [comment]
#773 
pending in next release
