### ISSUE TITLE
Документация - Overflow Menu 

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#760]
https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-overflowmenu--overflow-menu-base 
* 		- Selected - изменить контрол на стринг 
* 		
* 		- MenuWidth - изменить контрол на стринг 
* 		
* 		- Active - изменить контрол на стринг 
* 		
* 		- DisableSelectedOptionHighlight - изменить контрол на булеан 
* 		
* 		- isVisible - изменить контрол на булеан 
*

**Comment by syros** [comment]
#773 
pending in next release
