### ISSUE TITLE
Документация - Text Button

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#769]
https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-text-button--text-button-story-demo 
* 		- Не применяются контролы - не влияют на визуальную часть 
* 		
* 		- Text - изменить контрол на стринг 
* 		
* 		- DisplayRight - изменить контрол на булеан 
* 		
* 		- loading - изменить контрол на булеан 
*

**Comment by syros** [comment]
Добавлен пример с изменяемыми props: "Простой пример с изменяемыми свойствами"

#773 
pending in next release
