### ISSUE TITLE
Документация - Text Button Menu Story 

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#770]
https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-textbuttonmenu--text-button-menu-story-demo 
* 		- MenuWidth - изменить контрол на стринг 
* 		
* 		- Active - изменить контрол на стринг 
* 		
* 		- DisableSelectedOptionHighlight - изменить контрол на булеан 
* 		
* 		- isVisible - изменить контрол на булеан 
*

**Comment by syros** [comment]
#773 
pending in next release
