### ISSUE TITLE
Документация - Tooltip 

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#772]
https://admiralds.github.io/react-ui/?path=/docs/admiral-2-1-tooltip--tooltip-base 

6 / 13
* 		- WithDelay - не увидела разницу... Если смотреть в код на вкладке Story, то там для примера с задержкой не указан этот проп  + надо добавить описание 
*

**Comment by kateviditory** [comment]
Появление тултипа с задержкой или без полностью контролируется пользователем. Параметр withDelay был актуален в одной из прошлый версий тултипа, но на данный момент он удален из списка параметров. 

В сторибуке он отображается по ошибке, это будет исправлено.
