### ISSUE TITLE
Feature - Changelog - InputNumber

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#778]
Описаны новые правила ввода числовых значений в Input Number. При наличии префикса и суффикса, они окрашиваются в цвет Neutral 50 и не могут быть выделены и скопированы пользователем.

https://www.figma.com/file/EGEGZsx8WhdxpmFKu8J41G/Admiral-2.1-UI-Kit?node-id=146368-112749&t=hts8dBly9e7C4K5B-4

**Comment by kateviditory** [comment]
Сделано в рамках пул реквеста https://github.com/AdmiralDS/react-ui/pull/730
