### ISSUE TITLE
Feature - Changelog - Dropdown Menu 

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#780]
В компонент Dropdown Menu добавлены варианты Lines с иконкой справа и с двумя иконками
https://www.figma.com/file/EGEGZsx8WhdxpmFKu8J41G/Admiral-2.1-UI-Kit?node-id=146368-112749&t=hts8dBly9e7C4K5B-4

**Comment by Parasjona** [comment]
![image](https://user-images.githubusercontent.com/57989925/234787490-40fc5e7c-4f1b-4c94-858c-88531838a3d8.png)
