### ISSUE TITLE
[feature] - Suggest field длинный текст 

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#82]
suggest field длинный текст можно прочитать только наведясь мышью, а это не подходит для планшета. Хорошо бы сделать как в селекте. Ну и этого компонента еще проблема, что он при выборе опции выдает лишь строку текста, а не индекс опции. У нас этот компонент используется для поиска кода подразделения, а которые имеют разбивку на номер и текст. Приходится все время руками склевать данные в массив опций, а потому уже находить индекс конкретной опции по тексту

**Comment by Parasjona** [comment]
1. В соответствии с дизайн-системой в выпадающем списке опций SuggestInput не предусмотрено отображение текста в несколько строк.
2. Компонент не может возвращать индекс опции, т.к.введенное не обязательно должно находиться в списке опций, для фиксированных значений следует выбирать Select в режиме searchSelect
