### ISSUE TITLE
SelectField[mode="searchSelect"] при изменение children не происходит перерисовка

### ISSUE THREAD

**Issue by merioara-denis** [AdmiralDS/react-ui#839]
https://user-images.githubusercontent.com/88931298/230723854-24bfbf70-9251-489f-851d-023a44f57ee6.mp4

**Comment by merioara-denis** [comment]
Получил обратную связь от поддержки, где сказано что в компоненте реализована фильтрация по умолчанию, после добавления игнорирования фильтраций, всё работает корректно

в текущей реализаций инкапсулированной фильтраций приходиться плодить boilerplate в виде, мне кажется это избыточный и неочевидное поведение компонента 

```
const handleFilterItem = React.useCallback(() => true, []);

return (
    <SelectField
      mode="searchSelect"
      onFilterItem={handleFilterItem}
    >
        ...
  );
```

**Comment by syros** [comment]
Дефолтное поведение компонента предполагает фильтрацию среди массива существующих `option` по значению указанному в свойстве `value`. В случае записи в `value` любой другой информации, фильтрация будет кастомной, ее поведение переопределяется свойством `onFilterItem`, что вполне соответствует принципу открытости/закрытости.
