### ISSUE TITLE
MenuButton + Tooltip - нарушение позиционирования выпадающего меню

### ISSUE THREAD

**Issue by kdzone** [AdmiralDS/react-ui#857]
При подключении Tooltip к любой кнопке с выпадающим меню - меню уезжает при выпадении. 

![scr-tt-wm](https://user-images.githubusercontent.com/16046030/231581059-54683402-05ee-43dc-9a96-2b6d9d354f29.png)

Код во вложении:
[BugTooltip.zip](https://github.com/AdmiralDS/react-ui/files/11215888/BugTooltip.zip)

**Comment by kdzone** [comment]
"@admiral-ds/react-ui": "^4.10.0",

**Comment by DrUNE** [comment]
> В примере по ссылке меню не выпадает:
> 
> ![scr-tt-2](https://user-images.githubusercontent.com/16046030/231709681-d7126a9d-3ae2-4adc-a8a6-3b14461d4e4e.png)

по этой проблеме открыл новую задачу #859
