### ISSUE TITLE
Menu component prevent all `space`, `enter` and arrows press

### ISSUE THREAD

**Issue by zag7moon** [AdmiralDS/react-ui#866]
При помещении Input внутрь DropMenu по средствам renderContentProp, при открытом Menu невозможно ввести пробел в Input.

Полагаю это происходит из-за того, что компонент Menu создает обработчик, который превентит все нажатия на пробел. Это происходит тут: https://github.com/AdmiralDS/react-ui/blob/main/packages/react-ui/src/components/Menu/index.tsx#L210

**Comment by syros** [comment]
Поясните, с какой целью в меню в качестве пункта выбора встраивается поле ввода. Как используется данный кейс? ДС не предполагает такого. Для дальнейшей работы над проблемой нужен пример и обоснование такого использования.

**Comment by zag7moon** [comment]
@syros Инпут используется в качестве тригера для меню, то есть передается в проп `renderContentProp`.

**Comment by syros** [comment]
@zag7moon Вообще компонент создан для использования совместно с кнопками и поля ввода не планировались. Возможно Вам стоит использовать комбинацию Input + Menu с описанием собственной логики. Но все же, если будет пример кода с указанным кейсом, попробуем разобраться
