### ISSUE TITLE
Каким-то странным образом изменяется порядок options

### ISSUE THREAD

**Issue by merioara-denis** [AdmiralDS/react-ui#873]
https://user-images.githubusercontent.com/88931298/233834441-bb6bd9a4-fd44-4b48-9cfd-5689778e8893.mp4

---

До наведения

![image](https://user-images.githubusercontent.com/88931298/233834473-b00b2b37-de80-4151-b9d6-53d25b869549.png)

После наведения

![image](https://user-images.githubusercontent.com/88931298/233834502-0777f70f-a304-4ce7-baaf-2cb98892027f.png)

---

Поведение не очевидное и похоже на bug, как эту сортировку убрать ?

**Comment by merioara-denis** [comment]
![image](https://user-images.githubusercontent.com/88931298/233834910-b4da1c7e-36ba-4470-91a0-c77e42513b9f.png)

**Comment by syros** [comment]
Проверил на последней версии. Никаких странных сортировок не происходит, для выявления причин необходим пример с данными, независящими от внешних эффектов со стабильным воспроизведением данной проблемы.

**Comment by DreamerCoVi** [comment]
Прикладываю пример
https://stackblitz.com/edit/github-rrkrxg?file=components%2FCustomSelect.tsx


https://github.com/AdmiralDS/react-ui/assets/51414279/baa3662a-06c5-4e48-a85e-b424c04457af
