### ISSUE TITLE
Оптимизировать бандл либы

### ISSUE THREAD

**Issue by DrUNE** [AdmiralDS/react-ui#881]
На данный момент либа собирается одним бандлом с реэкспортом через index файл. Это не оптимально при последующем применении в проектах, например не позволяет качественно тришейкать по причине реэкспорта компонентов с возможными сайд эффектами. Предлагаю начать обсуждения возможных вариантов оптимизации.
![telegram-cloud-photo-size-2-5350713112996726989-y](https://user-images.githubusercontent.com/843964/234307801-6a93d3dc-c4c8-4b4f-a726-d9e1eb285090.jpg)

**Comment by DrUNE** [comment]
Предлагаю один из вариантов:
1. Бандл один но импорт компонентов происходит в изоляции, каждый по своему пути внутри либы. Этот вариант поможет значительно с тришейкингом
2. На каждый компонент своя либа со своей версией и зависимостью на центральную либу с темой. Этот вариант хорош при гранулярных обновлениях одного из компонентов (select,  table)
3.  Что-то среднее из первых двух. Есть либа с темой, к ней можно подключить либу с select или table или еще что-то, например как у [Palantir Blueprint](https://blueprintjs.com/docs/)

**Comment by garryk3** [comment]
Для начала, было бы отлично сделать программу минимум - разрешить экспорт из индексного файла, который реэкспортирует компоненты, по аналогии с https://github.com/mui/material-ui/blob/master/packages/mui-base/src/index.js

А так вариантов разделения, много.
1) 1 компонент - 1 репозиторий - на мой взгляд, не самый удачный. Компонентов много. И самим довольно сложно поддерживать, с учётом их зависимостей друг от друга. Да и импортировать к себе кучу пакетов не оч удобно, нужно будет следить, чтобы и версии этих пакетов не сильно отличались, чтобы не дублировались внутренние зависимости.  
2) выделение ядра из атомарных компонентов в отдельный пакет, второй пакет как и сейчас содержит все, используя выделенный пакет как зависимость. В чате как-то высказывались пожелания использовать только низкоуровневые компоненты для создания своих, это даст такую возможность.
3) Вынести из общей либы в отдельные пакеты крупные компоненты, которые могут не использоваться на постоянной основе большинством пользователей. Но тут нужен анализ использования библиотеки и компонентов.
4) создать монорепозиторий, как в примере с mui выше, разделить библиотеку на составляющие - ядро (низкоуровневые компоненты, темы, контекст, шрифты, утилиты - форматирование дат, к примеру:)), базовые компоненты, и сложные компоненты. С возможностью экспорта из packages
5) другие варианты:)

**Comment by DrUNE** [comment]
> Для начала, было бы отлично сделать программу минимум - разрешить экспорт из индексного файла, который реэкспортирует компоненты, по аналогии с https://github.com/mui/material-ui/blob/master/packages/mui-base/src/index.js
> 
Не очень понятно, что вы имели ввиду под программой минимум, ведь сейчас все именно так и сделано, как вы говорите, и это является проблемой от которой нужно уйти [https://github.com/AdmiralDS/react-ui/blob/main/packages/react-ui/src/index.ts](https://github.com/AdmiralDS/react-ui/blob/main/packages/react-ui/src/index.ts)

**Comment by garryk3** [comment]
> > Для начала, было бы отлично сделать программу минимум - разрешить экспорт из индексного файла, который реэкспортирует компоненты, по аналогии с https://github.com/mui/material-ui/blob/master/packages/mui-base/src/index.js
> 
> Не очень понятно, что вы имели ввиду под программой минимум, ведь сейчас все именно так и сделано, как вы говорите, и это является проблемой от которой нужно уйти https://github.com/AdmiralDS/react-ui/blob/main/packages/react-ui/src/index.ts

в https://github.com/AdmiralDS/react-ui/blob/main/packages/react-ui/package.json 
- в поле main выставлена ссылка на собранный пакет "dist/react-ui.cjs.js", 
- в поле exports ссылки, ведущие на собранные пакеты "exports": {
    "./package.json": "./package.json",
    ".": {
      "types": "./dist/index.d.ts",
      "require": "./dist/react-ui.cjs.js",
      "import": "./dist/react-ui.es.js"
    }
  }
  
  поэтому напрямую нельзя импортировать компоненты по описанному вами пути react-ui/src/index.ts

**Comment by DrUNE** [comment]
> * в поле main выставлена ссылка на собранный пакет "dist/react-ui.cjs.js",
> * в поле exports ссылки, ведущие на собранные пакеты "exports": {
>   "./package.json": "./package.json",
>   ".": {
>   "types": "./dist/index.d.ts",
>   "require": "./dist/react-ui.cjs.js",
>   "import": "./dist/react-ui.es.js"
>   }
>   }
>   поэтому напрямую нельзя импортировать компоненты по описанному вами пути react-ui/src/index.ts

Я еще больше запутался, пакет предназначен для импорта в проектах не только использующих typescript, поэтому существует сбилженый бандл, но если хотите настраивать у себя в проекте  typescript и бандлер для того что-бы импортить из сорца и транспайлить самостоятельно для этого (и нетолько для этого) в бандле лежит полный сорс и значит вы можете импортить из него как предлагаете.

**Comment by garryk3** [comment]
> > * в поле main выставлена ссылка на собранный пакет "dist/react-ui.cjs.js",
> > * в поле exports ссылки, ведущие на собранные пакеты "exports": {
> >   "./package.json": "./package.json",
> >   ".": {
> >   "types": "./dist/index.d.ts",
> >   "require": "./dist/react-ui.cjs.js",
> >   "import": "./dist/react-ui.es.js"
> >   }
> >   }
> >   поэтому напрямую нельзя импортировать компоненты по описанному вами пути react-ui/src/index.ts
> 
> Я еще больше запутался, пакет предназначен для импорта в проектах не только использующих typescript, поэтому существует сбилженый бандл, но если хотите настраивать у себя в проекте typescript и бандлер для того что-бы импортить из сорца и транспайлить самостоятельно для этого (и нетолько для этого) в бандле лежит полный сорс и значит вы можете импортить из него как предлагаете.

так разрешите экспорт из директории /src в package.json exports - webpack при сборке смотрит в него, eslint плагины смотрят  в него.

**Comment by DrUNE** [comment]
Никто и не запрещал импортить из сорца, хотите настраивать транспайлинг в точности как это сделано в либе - пожалуйста импортите из @admiral-ds/react-ui/src, настраивайте лоадеры для статических ресурсов и SVG и все. Вебпак и при сборке и eslint будут смотреть туда, откуда вы импортите. Но эта не та проблема которая обсуждается здесь.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/843964/235164489-207cd9a2-e92e-404e-812e-91f89459a223.png">

**Comment by garryk3** [comment]
> Никто и не запрещал импортить из сорца, хотите настраивать транспайлинг в точности как это сделано в либе - пожалуйста импортите из @admiral-ds/react-ui/src, настраивайте лоадеры для статических ресурсов и SVG и все. Вебпак и при сборке и eslint будут смотреть туда, откуда вы импортите. Но эта не та проблема которая обсуждается здесь.
> 
> <img width="1022" alt="image" src="https://user-images.githubusercontent.com/843964/235164489-207cd9a2-e92e-404e-812e-91f89459a223.png">
> 

Скрин с ошибками в терминале - это решение проблемы?

**Comment by DrUNE** [comment]
> > Никто и не запрещал импортить из сорца, хотите настраивать транспайлинг в точности как это сделано в либе - пожалуйста импортите из @admiral-ds/react-ui/src, настраивайте лоадеры для статических ресурсов и SVG и все. Вебпак и при сборке и eslint будут смотреть туда, откуда вы импортите. Но эта не та проблема которая обсуждается здесь.
> > <img alt="image" width="1022" src="https://user-images.githubusercontent.com/843964/235164489-207cd9a2-e92e-404e-812e-91f89459a223.png">
> 
> Скрин с ошибками в терминале - это решение проблемы?

Это проблемы, которые вас ожидают и вам придется их решить при импорте из сорца, скриншот показывает что импорт из сорца возможен

**Comment by garryk3** [comment]
> > > Никто и не запрещал импортить из сорца, хотите настраивать транспайлинг в точности как это сделано в либе - пожалуйста импортите из @admiral-ds/react-ui/src, настраивайте лоадеры для статических ресурсов и SVG и все. Вебпак и при сборке и eslint будут смотреть туда, откуда вы импортите. Но эта не та проблема которая обсуждается здесь.
> > > <img alt="image" width="1022" src="https://user-images.githubusercontent.com/843964/235164489-207cd9a2-e92e-404e-812e-91f89459a223.png">
> > 
> > Скрин с ошибками в терминале - это решение проблемы?
> 
> Это проблемы, которые вас ожидают и вам придется их решить при импорте из сорца, скриншот показывает что импорт из сорца возможен

Так эти проблемы я и пытаюсь решить, описав их выше в комментариях. Попробуйте их решить без фиксов в либе со стандартным набором инструментов - webpack, eslint, typescript. 
Вот тот же самый скрин, только без ошибок. Будет просто замечательно.

**Comment by DrUNE** [comment]
> > > > Никто и не запрещал импортить из сорца, хотите настраивать транспайлинг в точности как это сделано в либе - пожалуйста импортите из @admiral-ds/react-ui/src, настраивайте лоадеры для статических ресурсов и SVG и все. Вебпак и при сборке и eslint будут смотреть туда, откуда вы импортите. Но эта не та проблема которая обсуждается здесь.
> > > > <img alt="image" width="1022" src="https://user-images.githubusercontent.com/843964/235164489-207cd9a2-e92e-404e-812e-91f89459a223.png">
> > > 
> > > 
> > > Скрин с ошибками в терминале - это решение проблемы?
> > 
> > 
> > Это проблемы, которые вас ожидают и вам придется их решить при импорте из сорца, скриншот показывает что импорт из сорца возможен
> 
> Так эти проблемы я и пытаюсь решить, описав их выше в комментариях. Попробуйте их решить без фиксов в либе со стандартным набором инструментов - webpack, eslint, typescript. Вот тот же самый скрин, только без ошибок. Будет просто замечательно.

Здесь идет обсуждение оптимизации бандла, а не проблемы настройки typescript и транспайлера для сборки вашего проекта, когда импорт вы делаете из сорца, эффективно превращая бандл в транспортировщик сорс кода для вашего проекта.

**Comment by DrUNE** [comment]
Проект переведен на rollup бандлер. В результате библиотека начиная с 6.0.0 версии полностью поддерживает механизмы tree shaiking. Дополнительно отпадает необходимость настраивать кастомные лоадеры для транспайлинга SVG в бандле библиотеки
