### ISSUE TITLE
Input - неоднозначное поведение символов с апострофом

### ISSUE THREAD

**Issue by MerrickGit** [AdmiralDS/react-ui#898]
У компонента импута есть неоднозначное поведение при ввода апострофа после кириллических симоволов, у которых есть возможность указания апострофа.

![Анимация](https://github.com/AdmiralDS/react-ui/assets/12685148/ea8f0901-1673-47fe-9bec-900fa628eec8)

Как видно на gif картинке, при вводе латинского символа `а` и знака апострафа `, отображается два символа.

При ввода кирилического символа `a` и апострафа `, они соединяются в один символ à, необходимо привести к единому поведению, к отображению двух символов.

**Comment by DrUNE** [comment]
Вы набираете не символ апострофа, а символ [Грависа](https://ru.wikipedia.org/wiki/%D0%93%D1%80%D0%B0%D0%B2%D0%B8%D1%81) который существует в кирилической раскладке и для которого есть специальные символы в шрифте Адмирал, в латинской части шрифтов очевидно нет таких начертаний.
