### ISSUE TITLE
Changelog - Feature - Dropdown Menu

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#905]
В компонент Dropdown Menu добавлены варианты Lines с доп текстом и иконкой справа, с доп текстом и двумя иконками
https://www.figma.com/file/EGEGZsx8WhdxpmFKu8J41G/Admiral-2.1-UI-Kit?type=design&node-id=146368-112749&t=tcGEsxLVu3YwG8Ru-4

**Comment by Parasjona** [comment]
Дубликат
https://github.com/AdmiralDS/react-ui/issues/780
