### ISSUE TITLE
Changelog - Feature - Notifications

### ISSUE THREAD

**Issue by dariawish** [AdmiralDS/react-ui#911]
В компонентах Static Notifications, Toast Notifications, Line Notifications изменен отступ справа у контентной области с 12px на 16px.

https://www.figma.com/file/EGEGZsx8WhdxpmFKu8J41G/Admiral-2.1-UI-Kit?type=design&node-id=146368-112749&t=tcGEsxLVu3YwG8Ru-4

**Comment by Parasjona** [comment]
В коде реализовано
