### ISSUE TITLE
Сорс примеров в сторибуке должен содержать только импорты "как из библиотеки"

### ISSUE THREAD

**Issue by DrUNE** [AdmiralDS/react-ui#929]
На данный момент импорты в сорцах сторибука имеют вид `import { FieldSet } from '#src/components/form';` это вызывает затруднение в понимании того откуда идет импорт элемента или как должен выглядеть конечный импорт в проекте разработчика. Для решения этой проблемы предлагается для сторей ввести алиас имитирующий импорт из бандла библиотеки.

**Comment by DrUNE** [comment]
- [x] Menu 
- [ ] Select
- [ ] Input

**Comment by Parasjona** [comment]
- [ ] DateInput
- [ ] EditMode
- [ ] FileInput, FileUploader
- [ ] InputEx
- [ ] NumberInput
- [ ] PhoneNumberInput
- [ ] SliderInput
- [ ] SliderRange
- [ ] SuggestInput
- [ ] TextArea
- [ ] TextInput
- [ ] TimeInput

**Comment by Parasjona** [comment]
FornFields:

- [ ] CheckboxField
- [ ] DateField
- [ ] DateTimeField
- [ ] EditModeField
- [ ] FieldSet
- [ ] FileInputField
- [ ] InputExField
- [ ] InputField
- [ ] NumberInputField
- [ ] PhoneInputField
- [ ] ReadOnlyMaskedField
- [ ] SelectField
- [ ] SliderInputField
- [ ] SliderRangeField
- [ ] SuggestField
- [ ] TextField
- [ ] TimeField
