### ISSUE TITLE
Разрешение в exports package.json импорта из директории src

### ISSUE THREAD

**Issue by garryk3** [AdmiralDS/react-ui#932]
В текущей реализации поле exports в package.json, которое служит индикатором разрешенных импортов из пакета, не содержит разрешения на импорт модулей из директории src, что является проблемой при сборке, к примеру, webpack-ом.
https://webpack.js.org/guides/package-exports/

  "exports": {
    "./package.json": "./package.json",
    ".": {
      "types": "./dist/index.d.ts",
      "require": "./dist/react-ui.cjs.js",
      "import": "./dist/react-ui.es.js"
    }
  },
  
Требуется добавление дополнительного пути для импорта в поле exports, к примеру lib, src

  "exports": {
    "./lib": "./src/index.ts",
    "./src/*": "./src/components/*",
    "./package.json": "./package.json",
    ".": {
      "types": "./dist/index.d.ts",
      "require": "./dist/react-ui.cjs.js",
      "import": "./dist/react-ui.es.js"
    }
  },

**Comment by DrUNE** [comment]
Нет, такое не планируется делать, сделайте форк, поменяйте package.json предложенным вами способом и используйте ваш форк в ваших проектах. Причину мы с вами обсуждали тут https://github.com/AdmiralDS/react-ui/issues/881

**Comment by garryk3** [comment]
Все работает, проверено. Ну и что тут в целом не будет работать, если это просто добавление точки входа в пакет. И я же не прошу добавить какой-то крупный функционал, а одну строчку кода в файле.
