### ISSUE TITLE
Storybook - move stories to separate templates

### ISSUE THREAD

**Issue by Parasjona** [AdmiralDS/react-ui#958]

**Comment by Parasjona** [comment]
- [ ] Accordion
- [ ] Avatar
- [ ] AvatarGroup

**Comment by kateviditory** [comment]
- [ ] Badge
- [ ] Breadcrumbs

**Comment by Parasjona** [comment]
- [ ] DropMenu
- [ ] Menu
- [ ] Select

**Comment by Parasjona** [comment]
Input

- [ ] DateInput
- [ ] FileInput
- [ ] FileUploader
- [ ] InputEx
- [ ] PhoneNumberInput
- [ ] SuggestInput
- [ ] TextArea
- [ ] TextInput
- [ ] TimeInput
