### ISSUE TITLE
Обеспечить возможность отображения иконки(вертикальное многоточие) для контекстного меню(OverflowMenu) для всех строк в таблице (Table)

### ISSUE THREAD

**Issue by victordoshenko** [AdmiralDS/react-ui#969]
https://admiralds.github.io/react-ui/?path=/story/admiral-2-1-data-table-table--overflow-menu-example
На текущий момент иконка с многоточием отображается только при наведении курсора мыши. 
![image](https://github.com/AdmiralDS/react-ui/assets/19908367/1a13f53e-a28f-418e-b83b-3d3ac48fdf6c)
Предлагаю добавить новый параметр showOverflowMenuIcon: boolean; (по умолчанию false) для компонента Table. Если параметр не указан, то функционал работает как и прежде - иконка с многоточием отображается в таблице только при наведении курсора мыши. Если у компонента Table указан параметр  showOverflowMenuIcon = {true}, то иконка с многоточием отобразится для всех строк таблицы
![image](https://github.com/AdmiralDS/react-ui/assets/19908367/4a7d0d40-dbdc-4b3f-a8f9-cfad78d03425)

**Comment by Eldar-Gyzyev** [comment]
В ближайшее время решим каким образом сделать, что бы колонка была постоянно видна. Сделаем в дизайне и передадим в разработку.

**Comment by Eldar-Gyzyev** [comment]
Готово. В следующем спринте передам в разработку.

![image_2023-06-21_12-40-25](https://github.com/AdmiralDS/react-ui/assets/68902276/4b1be289-0d29-4e6d-8efe-83d6fbb3a831)
