### ISSUE TITLE
DataTable - добавить возможность создания типов кастомных статусов строк таблицы

### ISSUE THREAD

**Issue by MMPavlov** [AdmiralDS/react-ui#985]
Здравствуйте, хотелось бы иметь возможность красить строчки таблицы в разные цвета, например желтый `#FFF7F0 `и серый `#F1F2F4`

**Comment by Eldar-Gyzyev** [comment]
В документацию добавлено описание кастомных статусов строк
<img width="1216" alt="SCR-20230630-lhtn" src="https://github.com/AdmiralDS/react-ui/assets/68902276/f6268054-05d2-4b8a-935c-5f36a0cb6aa1">
